### ISSUE TITLE
Feat: Side panel

### ISSUE THREAD

**Issue by MildTomato** [supabase/ui#101]
For the form actions - I think the side over (side panel..?) component should have the actions at the bottom.
we could add these actually into the side over panel itself, just like the Modal.
We can open an issue to make this component in ui lib.

see tailwind ui example for actions at the bottom -

<img width="728" alt="Screenshot 2021-01-23 at 16 29 55" src="https://user-images.githubusercontent.com/8291514/105573394-42ad5500-5d98-11eb-95ee-d314de4838a7.png">

_Originally posted by @MildTomato in https://github.com/supabase/infrastructure/issues/716#issuecomment-765888967_

example of side panel in GTM.

https://user-images.githubusercontent.com/8291514/105700872-762ce280-5f44-11eb-9ecb-0feb5913ce40.mov

**Comment by mrkldshv** [comment]
@MildTomato Tailwind example is looking great 👍 I can play around with it to make it work if that's not assigned to anyone. 
I guess it should be quite generic component, but I'm wondering if we should create top and bottom parts (kinda header and footer with actions) in this component. What do you think about it?

**Comment by MildTomato** [comment]
@mrkldshv it's not assigned to anyone so feel free to have a crack at it.

I've already made a bit of a start on this component, it's in `src/components/SideOver`
You can see the [demo/docs of it here](http://ui.supabase.com/?path=/story/overlays-sideover--default)

It could do with some tidying up, and also needs migrating to typescript 😄 

> I guess it should be quite generic component, but I'm wondering if we should create top and bottom parts (kinda header and footer with actions) in this component. What do you think about it?

Absolutely, I've already tried to split it up into 'header', 'content' and 'footer'.

For the footer - I think ideally it would be good to do the same as the Modal component, which has the option for a [custom footer,](http://localhost:6006/?path=/story/overlays-modal--custom-footer) where you can just use your own ReactNode in a prop rather than use the generic 'submit' and 'cancel' buttons.

Take a look and see what you think.

If you have any ideas on how to handle the nesting of panels (like in the video above) that would be superb! 💯

**Comment by MildTomato** [comment]
Not sure if you've seen these - Supabase uses the side panel quite a lot in the table view in the dashboard, so we'd be quite keen to get those replaced with this new side panel if we can get it tidied up and support nesting.

![Screenshot 2021-01-25 at 21 30 49](https://user-images.githubusercontent.com/8291514/105712422-bb591080-5f54-11eb-9f34-dcee3f1168f8.png)

**Comment by mrkldshv** [comment]
@MildTomato Thanks for details! I'll try to make simple side over component and then we can think of handling nesting. Sounds good to you?

**Comment by MildTomato** [comment]
@mrkldshv awesome! ping me in here if you have any trouble.

**Comment by mrkldshv** [comment]
@MildTomato finishing it up 🚀 Got couple questions regarding colors for light and dark variants though, and I think we can discuss it in MR. Also, the only problem I have is adding top border (any border) to footer, it just does not apply for some reason. Did you had similar issue? I've tried to reproduce it on [playground](https://play.tailwindcss.com), but wasn't able to.

**Comment by MildTomato** [comment]
@mrkldshv yea i've had problems using borders,  especially tailwind classes like [`border-t`](https://tailwindcss.com/docs/border-width#class-reference), i wasn't actually able to reproduce it in tailwind playground though, it seemed like a problem with tailwind setup on this repo.

ah way round it could be (if you want to keep using tailwind classes) is to do something like this.

```css
/* Sidepanel.css */

.top-border-example {
  @apply border-gray-200 dark:border-dark-500;
  border-top-style: solid;
  border-top-width: 1px;
}
```

**Comment by MildTomato** [comment]
@mrkldshv [also had problems](https://github.com/supabase/ui/issues/5#issuecomment-751933242) using tailwind divide 😒    it's probably a related problem

**Comment by MildTomato** [comment]
Closing this 🚀  - thanks to @mrkldshv for this one 🔥 

nesting feature moved to #104
