### ISSUE TITLE
Feat: Accordian/collapse

### ISSUE THREAD

**Issue by MildTomato** [supabase/ui#102]
options could include:

• `expandIconPosition` prop - , for left or right chevron position
• ability to show 1, or multiple items (see Vercel for singular examples)
• `bordered ` prop - to show border/background version, if false then show no background/border
•`expandIcon` prop - ReactNode prop to use your own chevron icon

example of in use:

```JS
<Accordian
  defaultActiveId={['1']}
  onChange={callback}
  expandIconPosition="left"
>
  <Accordian.Item label="This is panel header 1" id="1">
    <div>{text}</div>
  </Accordian.Item>
  <Accordian.Item label="This is panel header 2" id="2">
    <div>{text}</div>
  </Accordian.Item>
  <Accordian.Item label="This is panel header 3" id="3">
    <div>{text}</div>
  </Accordian.Item>
</Accordian>
```

**vercel example**
https://user-images.githubusercontent.com/8291514/105789085-c051aa80-5fbc-11eb-85da-013549f5cd33.mov
![Screenshot 2021-01-26 at 10 07 16](https://user-images.githubusercontent.com/8291514/105789952-4de1ca00-5fbe-11eb-9dd1-f7069b97c013.png)

**antd example**
https://ant.design/components/collapse/
![Screenshot 2021-01-26 at 09 55 20](https://user-images.githubusercontent.com/8291514/105789070-b4fe7f00-5fbc-11eb-8834-23b06ad43b10.png)

**materializeUI example**
https://material-ui.com/components/accordion/
![Screenshot 2021-01-26 at 10 06 37](https://user-images.githubusercontent.com/8291514/105789924-3d315400-5fbe-11eb-847b-4a4ec632fa8e.png)

**Comment by angelmtztrc** [comment]
I was about to create an issue, but you had already anticipated me haha. Another good example of this could be the "Disclosure" component of Handless UI.

[Disclosure Component](https://headlessui.dev/react/disclosure)

![image](https://user-images.githubusercontent.com/65056245/114978073-54117500-9e4e-11eb-8a49-c1b8684b4361.png)

**Comment by MildTomato** [comment]
@angelmtztrc 👍 😂 

I think using either HeadlessUI or RadixUI for anything in this library is fine.

I'm just implementing the Select now with headlessui [Listbox](https://headlessui.dev/react/listbox).
It's pretty good - and having all the keyboard controls for free is awesome 💯

**Comment by MildTomato** [comment]
@angelmtztrc did you want to work on this?

**Comment by jonthomp** [comment]
@MildTomato @angelmtztrc I'll give this a go if it is available?

**Comment by angelmtztrc** [comment]
@jonthomp I have not a problem with that! I'm a little busy with other things, so go on!

**Comment by MildTomato** [comment]
@jonthomp go for it!
