### ISSUE TITLE
Feat: Side Panel nesting

### ISSUE THREAD

**Issue by MildTomato** [supabase/ui#104]
# Feature request

## Is your feature request related to a problem? Please describe.

SidePanel component to be nestable, so that a new side panel can be opened covering the last one.

nice to have:
to continually push the sidepanels underneath the active, top side panel.

example of side panel nesting behaviour in GTM.
https://user-images.githubusercontent.com/8291514/105700872-762ce280-5f44-11eb-9ecb-0feb5913ce40.mov

**Comment by MildTomato** [comment]
@mrkldshv are you interested in taking this one? otherwise I'll have a crack at it this weekend / next week

**Comment by mrkldshv** [comment]
hey @MildTomato, I am actually interested, but I haven't thought of the way to do it yet. Do you have any ideas?

**Comment by MildTomato** [comment]
I'm not sure this is a good idea (never tried it) but we could wrap each {children} with a context.provider, and the context provider basically just tells the SlideOver child component what index it is.
In the child component just +1 on the index and again, pass it down to the next one.

Each child component could then know how much to 'offset' to the right or left depending on which index number it is. 

I'm not sure that would work though as the context.consumer for deeply nested SlideOvers will probably just consume all the providers above it 😆 

I'll have a think about it.
