### ISSUE TITLE
Feat: Alert component

### ISSUE THREAD

**Issue by mrkldshv** [supabase/ui#108]
# Feature request

## Is your feature request related to a problem? Please describe.

It would be great to have some sort of alert component with couple variants, like: success, error, warning, info

## Describe the solution you'd like

Example: 
[Material UI](https://material-ui.com/components/alert/#alert)
![Screen Shot 2021-01-29 at 19 07 09](https://user-images.githubusercontent.com/47859603/106311298-31b38680-6265-11eb-930f-19f66535ba94.png)

I'm willing to help with this one if needed!

**Comment by MildTomato** [comment]
adding a few other examples here

![Screenshot 2021-02-01 at 11 13 51](https://user-images.githubusercontent.com/8291514/106411006-102de700-647f-11eb-86d6-001e51919b74.png)
![Screenshot 2021-02-01 at 11 17 03](https://user-images.githubusercontent.com/8291514/106410982-0c9a6000-647f-11eb-8e78-f66b42c3d15a.png)
![Screenshot 2021-02-01 at 11 17 00](https://user-images.githubusercontent.com/8291514/106410998-0e642380-647f-11eb-93ec-acf39bee2726.png)
![Screenshot 2021-02-01 at 11 16 54](https://user-images.githubusercontent.com/8291514/106411003-0efcba00-647f-11eb-8e8b-fab38d7df90d.png)

**Comment by MildTomato** [comment]
@mrkldshv I think this would be a great addition!
and we can also update the Auth component to use these as well.

some sasic requirements would probably be that it works a bit like Modal, in which you have the following 

`type`: "success" | "danger" | "warning" | "info"
dictates the color of the box, and the icon used.

`withIcon`: boolean
shows icon, could be off by default

`closable`: boolean
show a closable X button

`title`: string
main title, everything else could be in the body, unless we also add a `description` prop

**Comment by MildTomato** [comment]
I would probably also encourage that we use transparent colours on dark mode, like how Badge looks in dark mode.
(also see the last image [on the comment above](https://github.com/supabase/ui/issues/108#issuecomment-770536092))

**Comment by MildTomato** [comment]
@mrkldshv are you still interested in doing this?

**Comment by mrkldshv** [comment]
@MildTomato sorry for not being here for a while. Yeah, I am interested in this! Will submit PR soon.
