### ISSUE TITLE
Auth component

### ISSUE THREAD

**Issue by MildTomato** [supabase/ui#11]
# Feature request

Auth component that can use Supabase client

support for:
• social auth sign up / sign in
• email sign up / sign in form
• magic link form
• forgotten password form

A clear and concise description of what you want and what your use case is.

**Comment by MildTomato** [comment]
opened branch `feature/auth-component` for this

**Comment by kiwicopple** [comment]
Hey @MildTomato - can I check on this one? Does Thor's PR work? I'd love to use it for the Vercel application - https://github.com/supabase/next-server-components/issues/1

**Comment by MildTomato** [comment]
yea course!

I was going to style it up a bit more before merging but.. lets just merge it :D

**Comment by MildTomato** [comment]
@kiwicopple i haven't actually tried to use it yet - was going to check this afternoon.
