### ISSUE TITLE
Tab component should not have outline on focused

### ISSUE THREAD

**Issue by joshenlim** [supabase/ui#113]
# Bug report

I was just browsing through the storybook and noticed that selecting tabs of the tab component will show an outline on focus as such: 

![image](https://user-images.githubusercontent.com/19742402/106930354-671e0f80-6750-11eb-8182-5b3a4be3a9d4.png)

Thinking that we should probably not have any outline on focused? Not too sure which version of UI is the storybook currently on

**Comment by MildTomato** [comment]
thanks! 👍 


yea we need to remove the focus off the Button component, same for a few others

**Comment by MildTomato** [comment]
I'm going to remove the :focus styles on Button for now.

If anyone is looking for `:focus` styles for accessibility for this lib it might be best to open a new issue under a feature request.

**Comment by kiwicopple** [comment]
Hey @MildTomato, just want to check on this one

![image](https://user-images.githubusercontent.com/10214025/111054791-5e84cb80-84aa-11eb-9f5d-031ab5275d2c.png)


We're on version 0.15.0 in the dashboard, but saw this today on the Org Settings page

**Comment by MildTomato** [comment]
@kiwicopple yea just update to latest version and it will be fixed.
think we're on 0.21.0 now.

**Comment by kiwicopple** [comment]
Hmm I tried that.. Feel free to close again if I'm doing something wrong, but based on the [release commit](https://github.com/supabase/ui/pull/135), I think that we may need to apply focus styles:
https://tailwindcss.com/docs/preflight#buttons-have-a-default-outline

On UI version 0.21.0:

![Screenshot 2021-03-15 at 9 06 46 AM](https://user-images.githubusercontent.com/10214025/111091437-dff16200-856d-11eb-8352-b0bd833d0910.png)

**Comment by MildTomato** [comment]
@kiwicopple i'll have a look and test on infra.
guessing preflight is overriding the UI styles 😒

**Comment by MildTomato** [comment]
Yea got it, didn't realise preflight added a :focus style. 
I"ll release a fix right now 👍 
in v0.22.0

**Comment by kiwicopple** [comment]
thansk!
