### ISSUE TITLE
v0.12.0 release doesn't include "dist" folder

### ISSUE THREAD

**Issue by pyk** [supabase/ui#118]
# Bug report

v0.12.0 release doesn't include `dist` folder.

## Describe the bug

`@supabase/ui` module cannot be resolved.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Install `npm install @supabase/ui@0.12.0`
2. Import `import { Typography } from "@supabase/ui";`
3. See error

## Screenshots

<img width="1022" alt="Screen Shot 2021-02-07 at 07 48 06" src="https://user-images.githubusercontent.com/2213646/107133254-e2322200-6918-11eb-98c9-fee902a54133.png">

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by MildTomato** [comment]
thanks @pyk - we're taking a look at this

—

seems like semantic release did create the folder, although the build time is *a lot* longer, so maybe something went wrong somewhere else.

![Screenshot 2021-02-07 at 19 46 39](https://user-images.githubusercontent.com/8291514/107145574-8f3e8600-697d-11eb-8c77-4efbc0ccf18e.png)

I'll try doing a patch release and see if NPM is still missing the folder.

**Comment by FarazPatankar** [comment]
I just tried `0.12.1` and I am still seeing the same issue. Didn't want to create a separate thread but thought I'd still mention it.

**Comment by MildTomato** [comment]
👋  @FarazPatankar thanks - yea we're trying a few things out now. Seems like a bizarre issue with NPM.

**Comment by MildTomato** [comment]
I'll update in here once we've got it working 👍

**Comment by FarazPatankar** [comment]
Thank you, @MildTomato.

I switched to `0.11.2` just to test things out and I am seeing this with my import:
```Could not find a declaration file for module '@supabase/ui'. '/Users/farazpatankar/Desktop/dev/side-projects/botler/node_modules/@supabase/ui/dist/index.cjs.js' implicitly has an 'any' type.```

Not sure if it is related but my assumption was that this package has TS support?
