### ISSUE TITLE
feature: button with icon only

### ISSUE THREAD

**Issue by phamhieu** [supabase/ui#12]
# Feature request

## Is your feature request related to a problem? Please describe.

I need to create a button with icon on center. Trying to use icon props but it's left alignment.

<img width="686" alt="Screenshot 2021-01-05 at 5 14 08 PM" src="https://user-images.githubusercontent.com/689843/103628282-bd453a80-4f79-11eb-9222-d253da8915f9.png">
<img width="111" alt="Screenshot 2021-01-05 at 5 13 45 PM" src="https://user-images.githubusercontent.com/689843/103628283-be766780-4f79-11eb-8d8c-fa3a99241220.png">

## Describe the solution you'd like

icon should be in the center. And the same for loading indicator on loading state.
<img width="78" alt="Screenshot 2021-01-05 at 5 15 07 PM" src="https://user-images.githubusercontent.com/689843/103628296-c3d3b200-4f79-11eb-8ebc-6b85f25105fb.png">
<img width="100" alt="Screenshot 2021-01-05 at 5 19 03 PM" src="https://user-images.githubusercontent.com/689843/103628538-25941c00-4f7a-11eb-9e8e-5693006e7c43.png">

**Comment by MildTomato** [comment]
I think we also need a non rounded version, and we could do with a button type that matches that small button style in your screenshots.

**Comment by MildTomato** [comment]
@phamhieu 

If it's easier you can now use Icon component rather than using SVGs if it's in the [FeatherIcons](https://feathericons.com/) library

```javascript
import { Button, Icon } from '@supabase/ui`

function() {
  return (
     <Button icon={<Icon type={"MoreHorizontal"}/>}/>
)}
```

**Comment by phamhieu** [comment]
I use the latest `ui` lib version. But the rendered button is different:

<img width="119" alt="Screenshot 2021-01-06 at 9 45 25 AM" src="https://user-images.githubusercontent.com/689843/103719470-0c37b200-5004-11eb-8e32-0a2e05fb4ff1.png">

on hover

<img width="134" alt="Screenshot 2021-01-06 at 9 45 32 AM" src="https://user-images.githubusercontent.com/689843/103719476-0f32a280-5004-11eb-8073-4458a4dbc9e6.png">

my code:

<img width="323" alt="Screenshot 2021-01-06 at 9 45 39 AM" src="https://user-images.githubusercontent.com/689843/103719510-1ce82800-5004-11eb-9df7-3a31649f03ae.png">

**Comment by MildTomato** [comment]
@phamhieu probably working ok from v0.1.6

**Comment by MildTomato** [comment]
issue with Icon showing without color prop. fixing that now

**Comment by MildTomato** [comment]
Closing this because (i think...) it's fixed. Just reopen it if it persists.
