### ISSUE TITLE
Feat: declaration files

### ISSUE THREAD

**Issue by MildTomato** [supabase/ui#121]
Thank you, @MildTomato.

I switched to `0.11.2` just to test things out and I am seeing this with my import:
```Could not find a declaration file for module '@supabase/ui'. '/Users/farazpatankar/Desktop/dev/side-projects/botler/node_modules/@supabase/ui/dist/index.cjs.js' implicitly has an 'any' type.```

Not sure if it is related but my assumption was that this package has TS support?

_Originally posted by @FarazPatankar in https://github.com/supabase/ui/issues/118#issuecomment-774670728_

**Comment by MildTomato** [comment]
> I switched to 0.11.2 just to test things out and I am seeing this with my import:
> Could not find a declaration file for module '@supabase/ui'. '/Users/farazpatankar/Desktop/dev/side-projects/botler/node_modules/@supabase/ui/dist/index.cjs.js' implicitly has an 'any' type.
> 
> Not sure if it is related but my assumption was that this package has TS support?

@FarazPatankar moved your comment into this new issue 😄 

the dist folder had no type declaration files in it.
opened a PR #120 for this - should fix these warnings I think.

**Comment by MildTomato** [comment]
> Not sure if it is related but my assumption was that this package has TS support?

It should support TS, although I admit - I haven't actually been using the this UI library in a typescript project yet so I haven't really been looking at any TS issues.

**Comment by FarazPatankar** [comment]
Thanks again, @MildTomato. Just upgraded to `0.13.0` and everything works as expected. 🚀
