### ISSUE TITLE
[Auth] View parameter does not update properly

### ISSUE THREAD

**Issue by Etheonor** [supabase/ui#122]
When I use the Auth component, it seems that when I dynamicaly change the view parameter, it will not update the compontent. 

`<Auth
                  supabaseClient={supabase}
                  providers={["google"]}
                  socialLayout='horizontal'
                  socialButtonSize='xlarge'
                  view={view}
                  socialColors={true}
                />`

I have the same issue in your Storybook documentation, when I change the view parameter, the canvas does not change (but if I change other value, it works) https://ui.supabase.com/?path=/story/auth-auth--with-social-auth

Thank you!

**Comment by MildTomato** [comment]
Hey @Etheonor, thanks for the bug report.

Yea, I just had a look and it looks like any change in that prop won't affect the view.
I'll take a look at this later and fix it up so you can dynamically change the view.
