### ISSUE TITLE
Checkbox component support Icons

### ISSUE THREAD

**Issue by joshenlim** [supabase/ui#128]
# Feature request

In view of the storage stuffs I'm wondering if we could have it such that passing an Icon as a prop to a Checkbox component will show the Icon in place of the checkbox, until the user hovers over the checkbox

If the checkbox is selected, icon should remain hidden

**Comment by MildTomato** [comment]
I'm not sure about this.
I think it might be better to keep them separate, and just hide/show a checkbox on top of the Icon 'in app' rather than bloating the Checkbox component. Might also force
