### ISSUE TITLE
semantic release failed with wrong version number

### ISSUE THREAD

**Issue by phamhieu** [supabase/ui#13]
# Bug report

## Describe the bug

<img width="879" alt="Screenshot 2021-01-05 at 5 03 38 PM" src="https://user-images.githubusercontent.com/689843/103628909-9b988300-4f7a-11eb-97fe-460fbcdc39e6.png">
<img width="826" alt="Screenshot 2021-01-05 at 5 03 07 PM" src="https://user-images.githubusercontent.com/689843/103628928-9fc4a080-4f7a-11eb-88ce-f2a4c03ced7a.png">

I'm not sure why the version was wrong. 

After manually fix the version to 0.1.3 under `package.json` it works again.

**Comment by MildTomato** [comment]
We've been having trouble with semantic release. I accidentally created a v1.0 release and tag and it's caused issues ever since.

@soedirgo has been helping out :D

**Comment by soedirgo** [comment]
No need to manually update the version btw, semantic-release infers this from latest tag and commit messages. Though I guess it's confusing if package.json doesn't match...

**Comment by MildTomato** [comment]
It might be that @phamhieu also had tags locally if he pulled the repo a while ago.

![Screenshot 2021-01-05 at 19 36 27](https://user-images.githubusercontent.com/8291514/103641846-5467bd80-4f8d-11eb-97ab-ce3805938f17.png)

this is all i have now, hopefully when i next merge in shortly it will actually make a release on NPM

**Comment by MildTomato** [comment]
Seems to be fine now - releasing often and publishing to NPM. 
Closing issue.

**Comment by phamhieu** [comment]
It seems that i screw up auto release with my commits. Hope it's not.

@MildTomato  let me know if it is still working when you commit new code.

**Comment by MildTomato** [comment]
@phamhieu have you got any tags on this repo locally?
we had a v1.0.0 tag mistakenly added a while ago

**Comment by MildTomato** [comment]
@phamhieu its been working for me.
your [forwardRef](https://github.com/supabase/ui/pull/47) merged and released fine on v0.1.16 ?

**Comment by phamhieu** [comment]
<img width="403" alt="Screenshot 2021-01-11 at 11 00 34 AM" src="https://user-images.githubusercontent.com/689843/104143891-3e7a5280-53fc-11eb-9735-5a79ca7e6472.png">

yesterday i removed v1.0.0 tag already. But i'm not sure if i screw up anything.

**Comment by MildTomato** [comment]
that looks right to me 👍 

your merge yesterday looks like it auto released fine - or have i misunderstood something?

**Comment by phamhieu** [comment]
<img width="876" alt="Screenshot 2021-01-11 at 3 17 39 PM" src="https://user-images.githubusercontent.com/689843/104154577-392eff00-5420-11eb-84f7-c308c11af4e7.png">

i push a new commit and it doesn't create a new release 🤦

**Comment by soedirgo** [comment]
😂 I feel ya. `chore:` commits don't trigger a version update.

[Here's](https://www.notion.so/supabase/Releases-branching-and-commits-03233c1dbdc3443390d0f431f282be3f) a cheatsheet for semantic-release if it helps (skip the Branching section). This docs probably could do with more visibility though...

**Comment by MildTomato** [comment]
@soedirgo awesome!

I didn't even realise `chore:` doesn't trigger a release 😂 

sorry for the confusion @phamhieu
