### ISSUE TITLE
Inconsistent height for buttons between primary and default

### ISSUE THREAD

**Issue by joshenlim** [supabase/ui#131]
# Bug report

I'm wondering if this was intentional - primary type buttons are just slightly larger than default buttons (by 2px)

![image](https://user-images.githubusercontent.com/19742402/108249631-401ffe80-7190-11eb-954f-9decea349e77.png)

**Comment by MildTomato** [comment]
It's probably because 'default' doesn't have a border on it 🤔

**Comment by joshenlim** [comment]
ahhhh okay gotcha haha sorry, will close this issue

**Comment by MildTomato** [comment]
Ah sorry, we can still fix it @joshenlim 
They should all be consistent 😃 great spot !
