### ISSUE TITLE
Dropdown have automatic placement depending on its position relative to the view port

### ISSUE THREAD

**Issue by joshenlim** [supabase/ui#133]
# Feature request

If for example, the dropdown placement has been set to bottom, but it'll peak out of the bottom edge of its parent as such:
![image](https://user-images.githubusercontent.com/19742402/108885505-dcd81580-7642-11eb-8028-4ac041f2214b.png)

Thinking if we could have a flag to automatically flip the dropdown accordingly, in this case it's placement will be flipped to top instead

**Comment by MildTomato** [comment]
Looks like we'll have to fix this pretty soon 👍

**Comment by MildTomato** [comment]
https://wwayne.github.io/react-tooltip/
might be good example of doing it in this
