### ISSUE TITLE
suggestion: make inputs the same height as buttons

### ISSUE THREAD

**Issue by kiwicopple** [supabase/ui#136]
# For discussion

![image](https://user-images.githubusercontent.com/10214025/108988751-c926c080-76cf-11eb-9887-65d1fad2573b.png)

At the moment the default height of the Inputs and Buttons are different.

It makes alignment tricky. Is it a good idea to make these the same height? (my preference would be to make the vertical padding on the input smaller)

**Comment by MildTomato** [comment]
Maybe we introduce a size prop into Inputs, but they should match the sizes of the button sizes.

i was kind of expecting we'd need to do this anyway.

although as a quick win we can just match the input size to the default button size just to keep development moving.

**Comment by kiwicopple** [comment]
both these options sound great 👍
