### ISSUE TITLE
Way to have a min sized password?

### ISSUE THREAD

**Issue by Etheonor** [supabase/ui#137]
Right now with the current implementation of gotrue and with the supabase UI auth component, we can have a password of 1 character long. I think it's a big security issue and even if we can handle it on our side, it would be great if we had a basic implementation in the component.

Thanks!

**Comment by MildTomato** [comment]
Thanks @Etheonor, great suggestion this.

@awalias has anyone considered adding min-length to passwords in [@supabase/gotrue](https://github.com/supabase/gotrue)?
Even just something basic like 6 characters long as a bare min requirement.

We could implement some front end restrictions in the Auth component for now but maybe it should be an official requirement in the gotrue library?

**Comment by MildTomato** [comment]
Closing this as issue is now handled [here](https://github.com/supabase/gotrue/issues/74)
