### ISSUE TITLE
Dropdown child element to stop event propagation

### ISSUE THREAD

**Issue by joshenlim** [supabase/ui#147]
I'm currently using the Dropdown component as such:

```
<div onClick={() => event1}
  <Dropdown>
    <Button>
  </Dropdown>
</div>
```

Ideally, clicking on Button (the dropdown trigger element) shouldn't trigger the parent's onClick event (i.e. event1)

I've tried adding `onClick={(event) => event.stopPropagation})` to the Button and Dropdown component but I think it prevents the click event from triggering the dropdown to appear instead.

Although i'm also wondering if I'm using these correctly?

**Comment by MildTomato** [comment]
Don't really understand what you're trying to do here.

That parent <div> will probably trigger a click on the dropdown trigger, overlay and overlay contents of the dropdown.

I've started improving the docs for the UI lib, i feel they are not representing very well how a lot of things work together.

This is a better example on how to use dropdown

```
<Dropdown
    overlay={[
      <Dropdown.Item>
        <Text>Signed in as{' '}</Text><Text strong>tom@example.com{' '}</Text>
      </Dropdown.Item>,
      <Divider light />,
      <Menu>
        <Menu.Item icon={<IconSettings size="tiny" />}>
          Settings
        </Menu.Item>
        <Divider light />
        <Menu.Item>
          Something
        </Item>
        <Menu.Item>
          Something
        </Menu.Item>
      </Menu>,
      <Divider light />,
      <Dropdown.Item>
        <Button icon={<IconLogOut />} type="default">Log out</Button>
      </Dropdown.Item>
    ]}
  >
    <Button
      iconRight={<IconChevronDown />}
      type="outline"
    >
      Click for dropdown
    </Button>
  </Dropdown>
  ```

**Comment by joshenlim** [comment]
Ahh okay gotcha on this! Actually I may be using the component wrongly/reporting a wrong bug - will take a second look at my code sorry! Will close this issue for now
