### ISSUE TITLE
Buttons in customFooter do not align in Modal when one of them is set to loading

### ISSUE THREAD

**Issue by joshenlim** [supabase/ui#153]
# Bug report

Might just need an `align-center` on the custom footer?

![image](https://user-images.githubusercontent.com/19742402/110671677-c668b700-8209-11eb-96a5-9934ee21bc48.png)

![image](https://user-images.githubusercontent.com/19742402/110671645-bcdf4f00-8209-11eb-874b-025390952892.png)

**Comment by MildTomato** [comment]
that's weird.

try  out:
```
<Space>
<Button>Cancel</Button>
<Button>Delete</Button>
</Space>
```

**Comment by joshenlim** [comment]
Ahh sorry i keep forgetting to throw in code snippets for how I'm using it

![image](https://user-images.githubusercontent.com/19742402/110832475-4d836100-82d6-11eb-8f76-f78949166664.png)

This is how I was currently having the buttons in the custom footer - i think i see the problem now as well

But wrapping the buttons in `<Space>` is working perfectly! thanks so much! Will close this

**Comment by MildTomato** [comment]
@joshenlim it shouldn't of really done that anyway even outside a flexbox - we should fix it anyway.
I'll reopen this just so i don't forget about it

**Comment by MildTomato** [comment]
closing this, doesn't seem that important. your tailwind flex solution seems sufficient :D
