### ISSUE TITLE
Bug: style loading on production deployment

### ISSUE THREAD

**Issue by phamhieu** [supabase/ui#156]
# Bug report

## Describe the bug

When users do a prod deployment (ex: to vercel). Because of webpack splitChunks, @supabase/ui style will be loaded after the main app. 
It causes a glitch on the first load.

![CleanShot 2021-03-15 at 21 22 33](https://user-images.githubusercontent.com/689843/111288584-47e39d80-867f-11eb-84ab-d01c9eff4e43.gif)

**Comment by phamhieu** [comment]
We can update `rollup.config.js` to export CSS file that users can import into their apps to get those styles. 

This' a breaking change for current users. But it's a straight forward solution and many libraries doing this way.

**Comment by MildTomato** [comment]
@phamhieu does this mean 'all' of the CSS gets rolled into one file?

so for example, if someone just uses <Button> then all the styles for every component is still imported into their app?

**Comment by phamhieu** [comment]
yes, that's right

**Comment by MildTomato** [comment]
I'm not that keen on this - we put effort into splitting these up precisely so the library wouldn't import styles from components it didn't need.

This is also a SSR specific issue as well right?
Is there not any way we could use webpack in the target app to compile css of components into the SSR header ?

another solution maybe?
https://github.com/vercel/next.js/issues/13058#issuecomment-763746324

**Comment by phamhieu** [comment]
> Is there not any way we could use webpack in the target app to compile css of components into the SSR header ?

css already compiled into `@supabase-ui` component library. I don't think webpack can do any other optimisation.

Like tailwind, they can do optimisation on target app because users have to import all tailwind css into the target app and then use purge to strip unused tag.

**Comment by phamhieu** [comment]
<img width="229" alt="Screenshot 2021-03-17 at 9 29 01 AM" src="https://user-images.githubusercontent.com/689843/111400913-3d6ae780-8703-11eb-81da-49b62c4b2ce4.png">

like this css module, it's compiled into `js` file already.

**Comment by MildTomato** [comment]
> css already compiled into @supabase-ui component library. I don't think webpack can do any other optimisation.
I thought all the css modules are intact when built. 

![image](https://user-images.githubusercontent.com/8291514/111400914-3e9c1480-8703-11eb-8f1d-2d6591db969e.png)

open issue on css modules in npm packages 
https://github.com/vercel/next.js/issues/13282

**Comment by MildTomato** [comment]
> Like tailwind, they can do optimisation on target app because users have to import all tailwind css into the target app and then use purge to strip unused tag.

I don't understand, the ui lib doesn't rely on tailwind at all now

**Comment by phamhieu** [comment]
> I don't understand, the ui lib doesn't rely on tailwind at all now in target app.

it's example how tailwind can do css purge optimisation.

**Comment by ragnorc** [comment]
Also having this issue with Nextjs. How can we fix it?

**Comment by MildTomato** [comment]
We're using a new setup using tailwind in the target app now.
Closing this now.

### Supabase UI is moving.

We are moving the components to the main mono repo at [github.com/supabase/supabase](github.com/supabase/supabase).

**Comment by Nedi11** [comment]
This is not fixed

**Comment by MildTomato** [comment]
Hey @Nedi11 - Agreed, its not fixed. 

source code has moved to a new repo and issue is [tracked here](https://github.com/supabase/auth-ui/issues/99).

Sorry for the confusion!
