### ISSUE TITLE
Feat: Better Options Box on Selects

### ISSUE THREAD

**Issue by angelmtztrc** [supabase/ui#167]
# Feature request

## Is your feature request related to a problem? Please describe.

The current "Select" component has some problems, the "box" or options container has a background white, and the text too (at least in dark mode).

## Describe the solution you'd like

Will be better if we add a "custom" box or container, something like this:

![image](https://user-images.githubusercontent.com/65056245/113392157-ea737000-9351-11eb-81fc-942da0b287f3.png)

**Comment by MildTomato** [comment]
Hey @angelmtztrc 👋  

I don't really follow, the Select currently just uses a native Select so the options box is just provided by the browser.

What browser are you using?

On another note - we do intend to update this to be a custom 'non native' select, which could support things like inserting icons / react nodes into each Select.Option. If anybody would like to work on this that would be awesome. It should also include support for keyboard navigation.

**Comment by angelmtztrc** [comment]
I'm using Google Chrome, this is the preview of the select:
![Peek 2021-04-02 10-16](https://user-images.githubusercontent.com/65056245/113433626-d012b400-939c-11eb-9423-a2873a464dfd.gif)

**Comment by MildTomato** [comment]
@angelmtztrc nice one! thanks for the gif 👍

**Comment by volkandkaya** [comment]
I get that.

Also it isn't passing props down, so you can't disable it unless you use <option disabled>

**Comment by MildTomato** [comment]
Could I get some system information of you both 
@volkandkaya @angelmtztrc 

- OS: [e.g. macOS, Windows] and OS version
- Browser [e.g. chrome, safari] and browser version

**Comment by angelmtztrc** [comment]
I have the following:

OS: Ubuntu 20.04
Browser: Chrome 89

**Comment by volkandkaya** [comment]
I have the following:

OS: Ubuntu 20.04
Browser: Chrome 88

**Comment by MildTomato** [comment]
@volkandkaya @angelmtztrc thanks folks!

**Comment by MildTomato** [comment]
Not had time yet to look at this - if anyone would like to PR a fix for this it would be highly appreciated :D

**Comment by harshilparmar** [comment]
@MildTomato  I am thinking to contribute to this repo for the past week why not take this one. I would love to do this.

**Comment by MildTomato** [comment]
@harshilparmar Assigned the issue to you.

Just a heads up, we are going to update the Select component to be a styled dropdown one. (If you're interested on working that as well - please do leave a comment/submit a PR).

We can move this Select component and perhaps call it something like SelectNative if we implement the new Select.

**Comment by harshilparmar** [comment]
@MildTomato Is it ok to work on this issue? right!

**Comment by MildTomato** [comment]
Yea go for it! 😎

**Comment by harshilparmar** [comment]
@MildTomato I can't replicate the same issue in my local storybook !! Can you please help??

**Comment by MildTomato** [comment]
@harshilparmar I seem to be able to replicate it on BrowserStack with Chrome v88 on windows.
Seems to be a windows/ubuntu issue though only, and it doesn't affect mac versions of Chrome.
