### ISSUE TITLE
Bug: Default params not appearing in Storybook

### ISSUE THREAD

**Issue by MildTomato** [supabase/ui#175]
# Bug report

## Describe the bug

Default params are not appearing in the preview in Storybook.

![Screenshot 2021-04-16 at 10 19 30](https://user-images.githubusercontent.com/8291514/114962432-3d463f00-9e9d-11eb-9c62-fe170714eba3.png)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to http://localhost:6006/?path=/story/overlays-modal--default
2. Modal should show text in the buttons

## Expected behavior

Buttons are populated with the default params

```js
  onCancelText = 'Cancel',
  onConfirmText = 'Confirm',
  ```

**Comment by cmcWebCode40** [comment]
@MildTomato i would love to work on this issues  if its has not been taken , thanks

**Comment by MildTomato** [comment]
@cmcWebCode40 👍 assigned to you

**Comment by easy-street** [comment]
seems like this maybe be related to (typescript) prop type inference. afaict, props named `on<Anything>` are inferred as actions/event handlers.

changing the prop names resolves the issue ( `onCancelText` -> `cancelText` / `onConfirmText` -> `confirmText`).

so far i've only been able to find this alternate fix which feels clunky & brittle:
```
  // add to the default export in `.storybook/main,js`
  
  typescript: {
    reactDocgenTypescriptOptions: {
      propFilter: {
        skipPropsWithName: ['onCancelText', 'onConfirmText'],
      }
    },
  },
```

@MildTomato it does seem like it could be somewhat surprising for props named like typical event handlers to in fact be strings. maybe a PR to change the prop names would be the simplest way to go here?
