### ISSUE TITLE
Checkbox and label doesn't align vertically

### ISSUE THREAD

**Issue by joshenlim** [supabase/ui#179]
# Bug report

I noticed that the checkbox and its label doesn't align vertically? Wondering if I'm missing something - here's how I'm using it

```
<div>
    <Checkbox label="SELECT" />
</div>
```

![image](https://user-images.githubusercontent.com/19742402/115969696-cd0c7d00-a570-11eb-8657-4b1a73e29a08.png)

**Comment by joshenlim** [comment]
Might be something to do with label padding

![image](https://user-images.githubusercontent.com/19742402/115970136-21186100-a573-11eb-9c60-68df5f4cf521.png)

**Comment by MildTomato** [comment]
fixed in infra repo
