### ISSUE TITLE
Support redirectTo for the Auth component

### ISSUE THREAD

**Issue by ghoshnirmalya** [supabase/ui#182]
# Feature request
The [sign in](https://supabase.io/docs/reference/javascript/auth-signin#sign-in-with-redirect) supports **redirectTo**. However, the [Auth component](https://ui.supabase.io/components/auth) currently does not support that. It would be great if the Auth component supports that.

**Comment by Etheonor** [comment]
Really need this one too!

**Comment by MildTomato** [comment]
Sorry for late response on this. I'll add it in 😄

**Comment by bakerfugu** [comment]
Looks like this is still missing from the Props section of the docs https://ui.supabase.io/components/auth

**Comment by MildTomato** [comment]
@bakerfugu yep! we automatically plucked props with the website but it looks broken.
If anyone wants to take a look, the website is here https://github.com/supabase/supabase-ui-web
