### ISSUE TITLE
Dropdown is hidden in docs

### ISSUE THREAD

**Issue by Nick-Mazuk** [supabase/ui#185]
# Bug report

## Describe the bug

Dropdown component is behind code sample in docs.

## To Reproduce

1. Go to https://ui.supabase.com/components/dropdown#placement
2. Click on "Bottom center" (or any of those buttons)

## Expected behavior

Dropdown should always appear in front of every other item on the page.

## Screenshots

<img width="282" alt="Screen Shot 2021-05-05 at 4 49 12 PM" src="https://user-images.githubusercontent.com/5659171/117223104-d348f780-adc1-11eb-9310-7d7a1c843af9.png">

## System information

- OS: macOS 11.3.1
- Browser: Brave 1.23.75 using Chromium: 90.0.4430.93

## Additional context

One possible solution: I believe Vercel uses React Portal instead of inlining the dropdown into the DOM. They also use `translate3D` to create a new stacking context. Open their "menu" component and look at Chrome's dev tools.

This means, the dropdown will always be the last element on the page DOM-wise and therefore will automatically stack in front of everything else.

https://vercel.com/design/menu

**Comment by MildTomato** [comment]
> One possible solution: I believe Vercel uses React Portal instead of inlining the dropdown into the DOM. They also use translate3D to create a new stacking context. Open their "menu" component and look at Chrome's dev tools.

this is interesting - will take a look.

Alternatively we could just use radix or headless ui for this, and I assume these issues will be cleared up as well.
As a quick solution I might just throw in a high z-index value on it.
