### ISSUE TITLE
feature: button with fullwidth option

### ISSUE THREAD

**Issue by phamhieu** [supabase/ui#19]
# Feature request

## Is your feature request related to a problem? Please describe.

<img width="468" alt="Screenshot 2021-01-06 at 10 08 44 AM" src="https://user-images.githubusercontent.com/689843/103720835-3ccd1b00-5007-11eb-9006-b9d7d12160d7.png">

I need the button to fill the width and center label.

## Describe the solution you'd like

<img width="459" alt="Screenshot 2021-01-06 at 10 11 21 AM" src="https://user-images.githubusercontent.com/689843/103720978-8e75a580-5007-11eb-84fa-d5124a849ce6.png">

**Comment by MildTomato** [comment]
@phamhieu use the `block` prop

```
<Button block>I am full width</Button>
```

I'll close this for now. just reopen it if it doesn't work
