### ISSUE TITLE
Chore: add arrows to dropdowns

### ISSUE THREAD

**Issue by MildTomato** [supabase/ui#198]
# Chore

## Describe the chore

Add arrows to dropdown overlay panels

![Screenshot 2021-05-19 at 20 34 51](https://user-images.githubusercontent.com/8291514/118813412-acbaae80-b8e1-11eb-8ccb-bd6e47ca75d7.png)
https://radix-ui.com/primitives/docs/components/dropdown-menu#arrow

**Comment by ankitjena** [comment]
Hey, @MildTomato Would like to contribute. Is there some place I can refer to for setting up the project
Right now I am doing the following
- Forked the repo and run `npm build`
- npm link inside the repo
- add link in a test folder using `npm link @supabase/ui`

But I seem to be getting an error
![image](https://user-images.githubusercontent.com/23580602/119252030-745bee80-bbc7-11eb-9e8e-0554789befbe.png)

**Comment by MildTomato** [comment]
@ankitjena sorry for the late reply!

Yep, I've had the same problem as you're having.

To be honest, I've mainly been testing and playing around with components inside storybook, but we should really get into the habit soon of making components and road testing them in react apps on the fly - but this problem you mentioned keeps happening and I'm not super familiar with it.

I wrote up a fix that (sometimes) works for this. I think this tends to work as long as your using the same version of react and react-dom in both the ui library and also the target app your testing it in.
https://github.com/supabase/ui/blob/develop/development.md#common-issues

If you're struggling with that though, I'd suggest just using storybook to preview the components.
You can run storybook with `npm run storybook` and it should be served on `localhost:6006`

**Comment by ankitjena** [comment]
@MildTomato Sorry for the late response on my end as well, busy week! Thanks for instructions. I went the easier route with storybook and made a PR, do review it if possible.
