### ISSUE TITLE
Supabase UI Auth example (readme) - doesn't work as is

### ISSUE THREAD

**Issue by pdwittig** [supabase/ui#199]
# Improve documentation

## Link 

https://github.com/supabase/ui/blob/develop/README.md

## Describe the problem
The Auth UI example doesn't work as is. Specifically, `supabaseClient` needs to be passed in to the `Auth` component. Also the `Container` component is not actually used in the example.
```
export default function Home() {
  return (
    <Auth.UserContextProvider supabaseClient={supabase}>
      <Auth providers={['facebook', 'github']}/>
    </Auth.UserContextProvider>
  );
};
```

## Describe the improvement

This is what worked for me:

```
export default function Home() {
  return (
    <Auth.UserContextProvider supabaseClient={supabase}>
      <Container supabaseClient={supabase}>
        <Auth providers={['facebook', 'github']} supabaseClient={supabase}/>
      </Container>
    </Auth.UserContextProvider>
  );
};
```

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by MildTomato** [comment]
Thanks @pdwittig - this is my fault. 
I'll amend the readme, unless you want to PR a change yourself?

**Comment by Vandivier** [comment]
looks like @MildTomato is on it! admittedly I'm confused why we need the contextProvider if we are going to pass the object into the next layer directly

**Comment by MildTomato** [comment]
@Vandivier I suppose it looks a bit strange

there's consumer in the Auth component which is where the Provider is actually used.
it just allows someone to easily check if someone is logged in.
```js
 const { user } = Auth.useUser();
 if (user) {
  // show profile....
 }
```

A better example might be our NextJS example which shows all the working code for Supabase Auth integration, without using any @supabase/ui, bit easier to see what's going on.
https://github.com/supabase/supabase/tree/master/examples/nextjs-auth
