### ISSUE TITLE
feat: Avatar component

### ISSUE THREAD

**Issue by MildTomato** [supabase/ui#210]
# Feature request

## Is your feature request related to a problem? Please describe.

Inspiration from 
https://ant.design/components/avatar/

See https://github.com/supabase/ui/pull/208 thread for more details as well

**Comment by MildTomato** [comment]
Adding this here for you @galanteria01 🚀

**Comment by galanteria01** [comment]
@MildTomato 
Thank you sir.

**Comment by MildTomato** [comment]
@galanteria01 as a heads up - we're going to be adding in user profile avatars into the project view in the supabase dashboard, so we'll possibly be using this component to show which team members are currently online viewing the same project.

I'll try and expand this issue above with a more detailed spec of what this component, but feel free to crack on if you are keen to get some basic functionality in place.

**Comment by galanteria01** [comment]
@MildTomato 
I have made a working Avatar component with fallbacks including Image, Icon, First letter of child text and lastly a user icon with greyish background uptill now. Considering your opinion what progress i can make to create a PR?
GroupAvatar is the one I'm thinking about, Your suggestions would be helpful.
Thank you sir.

**Comment by MildTomato** [comment]
@galanteria01 yep, sounds good.

A group avatar subcomponent would be great.
something like:

```js
<Avatar.Group>
  <Avatar />
  <Avatar />
  <Avatar />
<Avatar.Group/>
```

**Comment by galanteria01** [comment]
Yes sir.
And even mapping quite a lot of elements inside it would be easier. I would
implement group and test it. And a prop of onHover on the extension element
could be given as callback. If user want to do something else he can else
fallback would be dropUp.

**Comment by MildTomato** [comment]
@galanteria01 awesome, feel free to PR whenever - even a work in progress if you like.

**Comment by galanteria01** [comment]
@MildTomato 
Yes sir will PR tomorrow. Cleaning up implementation with tailwindcss and separating in Module.css.

**Comment by MildTomato** [comment]
@galanteria01 are you still keen to work on this? we are looking to use this component in the next few days.
Happy to take this one if you're busy.

**Comment by galanteria01** [comment]
Hello sir. Actually it was first week of my internship so was little busy.
Tomorrow will submit patch . Sorry for delay sir.

**Comment by MildTomato** [comment]
Closing this as the component has been started on
