### ISSUE TITLE
bug: clean install of project does not work

### ISSUE THREAD

**Issue by YashKandalkar** [supabase/ui#212]
# Bug report

## Describe the bug

npm throws a resolution error when doing a fresh install (deleting package-lock.json and running `npm install`)

## To Reproduce

1. Clone repo
2. Delete package-lock.json
3. run `npm install`

## Expected behavior

Proper package-lock.json to be generated without errors

## Screenshots

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @supabase/ui@0.1.3
npm ERR! Found: postcss@7.0.35
npm ERR! node_modules/postcss
npm ERR!   dev postcss@"^7.0.35" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer postcss@"^8.1.0" from postcss-modules-values@4.0.0
npm ERR! node_modules/postcss-modules-values
npm ERR!   dev postcss-modules-values@"^4.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

## System information

- OS: Windows
- Version of Node.js: v15.12.0

## Additional context

When trying to resolve deps, 
Got more resolution errors.

**Comment by YashKandalkar** [comment]
@MildTomato I just wanted to run `npm test` to run tests, was planning to write tests for components but this resolutions needs to be fixed for `npm test` to run properly

**Comment by MildTomato** [comment]
Might not be related, but for some reason we've had to run `npm install --legacy-peer-deps` when we upgraded tailwind / postcss, as it showed the error in the original post above.

**Comment by i-pip** [comment]
After trying a bunch of things, downgrading Node from v14 to v12 was the only thing that worked for me. 
It appears npm v7 (which comes with Node v14) upwards is a lot stricter with dependency resolution errors than npm v6 (Node v12)... [using a Node version manager helped here](https://github.com/Schniz/fnm/). 

This is a hack though, a better / long-term solution would be to upgrade dependencies and resolve resolution errors.

**Comment by MildTomato** [comment]
It seems like these issues are related mostly to Windows.
I'm working on OSX so I don't see any of these problems on my side.

@i-pip are you working on windows OS as well?

**Comment by MildTomato** [comment]
related - https://github.com/supabase/ui/pull/214#issuecomment-864581231

**Comment by i-pip** [comment]
> It seems like these issues are related mostly to Windows.
> I'm working on OSX so I don't see any of these problems on my side.
> 
> @i-pip are you working on windows OS as well?

@MildTomato I'm also working on OSX (Big Sur v 11.4). I tried it with Node 14.17.0 and 16.3.0 and both still give the same errors. 

Then I tried it on my Ubuntu VM running Node v14.17.0 and it works just fine there 🤭

So definitely not a Node version issue - more like something wrong with my own environment
