### ISSUE TITLE
[Bug] library loads all css into head

### ISSUE THREAD

**Issue by MildTomato** [supabase/ui#217]
# Bug report

## Describe the bug

All CSS is injected into the <head> regardless as to wether it has been used or not.

![Screenshot 2021-06-03 at 16 38 46](https://user-images.githubusercontent.com/8291514/120614972-61300500-c48a-11eb-880b-bf3544f288a1.png)

Using version 0.27.2
Using in NextJS

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a nextjs app
2. import 1 component, like Button
3. You'll see all the styles loaded into head

## Expected behavior

To only use styles that are in use

**Comment by jonthomp** [comment]
🙋🏻‍♂️

**Comment by MildTomato** [comment]
@jonthomp I'm pretty sure we had this working before though

**Comment by MildTomato** [comment]
The auth component has been moved to it's own repo and package.
[github.com/supabase-community/auth-ui](github.com/supabase-community/auth-ui).
You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).
