### ISSUE TITLE
Sidepanels not working on documention page

### ISSUE THREAD

**Issue by pichichi91** [supabase/ui#222]
# Feature request

## Is your feature request related to a problem? Please describe.

Not sure if it's a feature request or an bug report, as I don't know how much "ready" the sidepanels ([https://ui.supabase.com/components/sidepanel](https://ui.supabase.com/components/sidepanel)) are.

1. On the documentation site they keep appearing on really strange positions, especially on the lower areas on the page:

![image](https://user-images.githubusercontent.com/7605468/120914100-1be32180-c69c-11eb-8386-f658b91ff8fc.png)

2. scrollbars aren't really needed all time in the sidepanels
3. Issues with z-index and codeblock:

![image](https://user-images.githubusercontent.com/7605468/120914277-61ecb500-c69d-11eb-944f-733655fb8f7c.png)

4. There's a flicking when opening and closing the Sidebars 

## Describe the solution you'd like

1. position:fixed instead of absolute could be working there:

```css
.sbui-sidepanel-container {
...
position: fixed;
... 
}
```

2. also .sbui-space-col has `overflow-y: scroll`, wouldn't that design wise be an overflow-y: auto (a scrollbar would only visible if needed, now it's always there) 
3.  `.sbui-sidepanel-container ` needs an z-Index of atleast 1

**Comment by MildTomato** [comment]
Ahh @pichichi91 thanks for the bug report.

I think the docs site is using an old version of SupabaseUI. I'll update it 👍
