### ISSUE TITLE
Support forwardRefs for Input component

### ISSUE THREAD

**Issue by huntedman** [supabase/ui#226]
# Feature request

## Is your feature request related to a problem? Please describe.

Support React.forwardRef() for Input component

## Describe the solution you'd like

Currently, passing a ref to the input field fails.

**Comment by jonthomp** [comment]
@huntedman there is an `inputRef` prop that you can use at the moment but I do agree more `forwardRef` support would be great

**Comment by huntedman** [comment]
> @huntedman there is an `inputRef` prop that you can use at the moment but I do agree more `forwardRef` support would be great

I'd be happy to open a PR about it, but I don't know how to "type" it.
I checked the source code and I encountered this:

```
function Input({...})

function TextArea({...})

// I'm talking about this line
// Where we assign a text area to an input component?
// Wat?
Input.TextArea = TextArea
```
Can anyone tell me what is this weird assignment syntax? I'm new to JS/TS and It's got me puzzled 😕. I don't even know how to google this.

**Comment by MildTomato** [comment]
@huntedman looking at this now I'm even wondering why I did this originally.

I think I made the TextArea a subcomponent because I was used to AntDesign doing the same thing.
But there's no real reason why it should be a subcomponent, and could just be part of the main Input function but use 'textarea' as a type, which makes more sense probably.

**Comment by Dhaiwat10** [comment]
I'd be interested in picking this one up if it still needs to be taken care of.

**Comment by MildTomato** [comment]
There's a RFC on implementing better ref support [here](https://github.com/supabase/ui/pull/225)
Might be good to check that out and add your comments

**Comment by Dhaiwat10** [comment]
Looks good. Should we wait for that PR to get merged? Since we'll be needing the util method & the type that they've created there?

**Comment by huntedman** [comment]
> @Dhaiwat10
> There's a RFC on implementing better ref support [here](https://github.com/supabase/ui/pull/225)
> Might be good to check that out and add your comments

I'll wait for the PR then.
Thank you for building such an awesome component library, and also enlightening me about "Subcomponents" 😅.

**Comment by MildTomato** [comment]
I'm not entirely sure subcomponents were a good idea though 😅  I think in some cases its not great for tree-shaking, but its a nice way to package a few things together like the Radio component. 

Perhaps they should all be separate components to minimise the footprint of the library.
