### ISSUE TITLE
Feature: Tabs

### ISSUE THREAD

**Issue by joshenlim** [supabase/ui#23]
# Feature request

Thinking of using `ui` in repository.surf as well - wondering if we can have tabs:
https://tailwindui.com/components/application-ui/navigation/tabs#component-556317db33900f6182a5f45cd9b50300

![image](https://user-images.githubusercontent.com/19742402/103742719-40c46180-5036-11eb-9261-6c1ab3bc115b.png)

**Comment by MildTomato** [comment]
@joshenlim  what do you think? 

I'm thinking we add something like <Tab.Panel> which can support children.
So then when a tab is clicked, the corresponding panel is shown.

```javascript
<Tabs defaultActiveKey="1" onChange={callback}>
    <Tab.Panel label="Tab 1" key="1">
      Content of Tab Panel 1
    </Tab.Panel>
    <Tab.Panel label="Tab 2" key="2">
      Content of Tab Panel 2
    </Tab.Panel>
    <Tab.Panel label="Tab 3" key="3">
      Content of Tab Panel 3
    </Tab.Panel>
  </Tabs>
  ```
  
  We could also support having no children, 
  in case the tab menu wants to be used alone and the callbacks could be used to control what content is shown.
  ```javascript
<Tabs activeKey="1" onChange={callback}>
    <Tab.Panel label="Tab 1" key="1"/>
    <Tab.Panel label="Tab 2" key="2"/>
    <Tab.Panel label="Tab 3" key="3"/>
  </Tabs>

  // options version with array
  // our checkbox and radio groups work like this as well
  <Tabs 
  activeKey="1" 
  onChange={callback}
  options={[
    {
      label:'Tab 1'
      key: '1'
    },
    // ...
  ]}
  />
  ```

**Comment by joshenlim** [comment]
yeah i think this sounds good - having the option for either no children or with children, gives some flexibility.

If thats the case does it also imply that if no children is passed - Each Tab.Panel will have its own styling
But if a children is provided, - Each Tab.panel will not have its own styling, it'll depend on the children's styles for the looks

**Comment by MildTomato** [comment]
first iteration done.

will make a new issue for 'card' tabs, like we have in the supabase dashboard
