### ISSUE TITLE
[Feat] Date / Time / Date range picker

### ISSUE THREAD

**Issue by MildTomato** [supabase/ui#234]
# Feature request

## Is your feature request related to a problem? Please describe.

New data input component that can handle date, time and date ranges.

Will also be used to support postgres formats: `timestamp`, `timestampz`, `date`, `timetz` and `time`.

**Comment by neotan** [comment]
Hi @MildTomato , I'm keen on picking this up if possible. Before that, may I ask few questions:
1. is there any mockup/prototype for reference? 
2. any specific features required? Or we follow some other UI libs' features?
3. any other things noticeable?

Thank you!
