### ISSUE TITLE
'Auth' cannot be used as a JSX component when using React(NextJs) with typescript

### ISSUE THREAD

**Issue by manyeya** [supabase/ui#236]
# Bug report

<img width="816" alt="Screenshot 2021-07-02 at 16 51 58" src="https://user-images.githubusercontent.com/42819801/124292951-6c905200-db56-11eb-9e6d-5390624a5537.png">

## Describe the bug

Auth component returns type 'Element | undefined' which is not a valid JSX element

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. setup React(NextJs) with Typescript
2. setup superbase and try out default example
3. See error

**Comment by MildTomato** [comment]
that's weird, thought i would of seen this before now. 
thanks for the PR @manyeya 🔥

**Comment by manyeya** [comment]
Happy to be of help 🙏🏾

**Comment by MildTomato** [comment]
Just whipped up a nextjs typescript and I'm seeing the same thing, and also in the storybook stories 🙈

**Comment by manyeya** [comment]
its a pretty minor thang , am not suprised  you missed it
