### ISSUE TITLE
Feature: Large Radio + Checkbox Group buttons

### ISSUE THREAD

**Issue by MildTomato** [supabase/ui#24]
# Feature request

![Screenshot 2021-01-06 at 18 08 18](https://user-images.githubusercontent.com/8291514/103756374-3ca23f00-504a-11eb-800a-93cf12f8ccab.png)

![Screenshot 2021-01-06 at 18 07 50](https://user-images.githubusercontent.com/8291514/103756284-1c728000-504a-11eb-817f-4c6d8ffbe5ee.png)

**Comment by pichichi91** [comment]
Hi @MildTomato is this still a thing? I was looking for a "good first issue" and could would work on this and create a first PR for this

![image](https://user-images.githubusercontent.com/7605468/120913308-6bbeea00-c696-11eb-9925-de49f982d8ac.png)

**Comment by MildTomato** [comment]
@pichichi91 yes please. that would be awesome! 🔥 
I'll assign you the issue

**Comment by aggmoulik** [comment]
Hey @MildTomato, I think the PR was dropped for unavailability reason from the contributor, so can I complete the PR resuming his work.

**Comment by MildTomato** [comment]
### Supabase UI is moving.

We are moving the components to the main mono repo at [github.com/supabase/supabase](github.com/supabase/supabase).

This issue is not in our current plans to support right now.
Thanks for all the contributions and comments so far.
