### ISSUE TITLE
Page number input field obstructed by spinner on Firefox

### ISSUE THREAD

**Issue by sahil-shubham** [supabase/ui#242]
# Page number input field obstructed by spinner on Firefox

When dealing with a large data set, it's hard to know which page one is on due to the input field being obstructed on Firefox. One is only able to see the first letter of the page number as can be seen in the screenshot below. 

![image](https://user-images.githubusercontent.com/60931421/124520969-a63db300-de0b-11eb-9919-173f92c5db68.png)

## Expected behavior

- The up and down arrows (spinner) shouldn't be visible, like on Chrome.
![image](https://user-images.githubusercontent.com/60931421/124521774-60361e80-de0e-11eb-943a-9e2f7941bfab.png)

- [RELATED] It should also be easier to move the last page of the data by clicking on the left arrow when on the first page. 

## System information

- Firefox v89

## How to fix
Adding `-moz-appearance: textfield` should fix this issue with the spinner, and to make the page number go to max/min when already on the first/last page one would have to add a condition in the onClick function of arrow buttons.

**Comment by harshilparmar** [comment]
(Suggestion) : From my understanding removing the number spinner is not the right solution instead setting that by giving some css. And for pagination issues, It should have another two-button for the first and last page from a UX perspective.

**Comment by MildTomato** [comment]
thanks @sahil-shubham 👍 

we had some CSS added for the arrows but they didn't work well when changing the size of the input.
more than happy to get this back in and working - and also make sure we hide arrows when they are not needed.

I think on the [Supabase Grid library](https://github.com/supabase/grid), there's an argument we probably shouldn't have a number input at all, and just concentrate on having a 'first page', 'next page', 'previous page', 'last page' - mainly because there might not be much benefit of jumping to pages, especially if you have a few million rows in a table.

Regardless, the NumberInput component should be fixed anyway for firefox 👍

**Comment by sahil-shubham** [comment]
> there's an argument we probably shouldn't have a number input at all, and just concentrate on having a 'first page', 'next page', 'previous page', 'last page' - mainly because there might not be much benefit of jumping to pages, especially if you have a few million rows in a table.

This seems like a better way to handle this, thank you for pointing this out. 

Is someone working on this issue? If  not, I  would like to work on this.

**Comment by MildTomato** [comment]
@sahil-shubham for changes on the table view, you can submit pull requests on https://github.com/supabase/grid
I think @phamhieu would like to see 'first page', 'last page' functionality being added.

**Comment by MildTomato** [comment]
### Supabase UI is being deprecated.

As part of that, we are closing Pull Requests in this repo for now.

If you'd like to still make these changes, you could consider making these changes in https://github.com/supabase/supabase/tree/master/packages/ui

---

We are moving the components to the main mono repo at [https://github.com/supabase/supabase](https://github.com/supabase/supabase).

The auth component has been moved to it's own repo and package. [https://github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).
