### ISSUE TITLE
Allow Auth component to hide email auth

### ISSUE THREAD

**Issue by MildTomato** [supabase/ui#244]
# Feature request

## Is your feature request related to a problem? Please describe.

https://github.com/supabase/supabase/discussions/2318

"Is it possible to disable the email/password log in boxes in the Supabase UI? I'm trying to only have a single OAuth login available, but can't find where I could disable the email/password"

## Describe the solution you'd like

Add a prop to disable/hide the email auth functionality.
May need to change how the layout looks for this to look ok.

## Additional context

As an added bonus, the email and 0auth could be split up as exportable components, so you could import just the functionality you need, minimising the footprint of the component. 
Maybe best as a future update.

**Comment by mstibbard** [comment]
You work amazingly quickly @harshcut!

I'm happy to open a seperate issue if that's preferred, but could we also split out the magic link option? My personal preference on new sites is third-party auth + magic link.

**Comment by MildTomato** [comment]
@mstibbard yep, fancy opening a PR for that? I can merge in @harshcut PR now

**Comment by MildTomato** [comment]
@mstibbard https://github.com/supabase/ui/issues/246
