### ISSUE TITLE
Scroll doesn't get reset when selecting a different component from the sidebar in docs

### ISSUE THREAD

**Issue by Dhaiwat10** [supabase/ui#252]
# Bug report

## Describe the bug
The window scroll doesn't get reset when selecting a different component from the sidebar in docs. So you have to manually scroll back to top if you had previously scrolled down. Attaching a screen recording below.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://ui.supabase.io/components/button
2. Scroll to bottom
3. Click on any other component on the sidebar

## Expected behavior

The scroll should be reset to the top, I guess? This is kind of a pain in the butt when trying to go through the docs

## Screenshots

Screen recording: 

https://user-images.githubusercontent.com/39617427/127593837-7dd0ba44-9423-4ede-912d-0920a0429864.mov

## System information

- OS: macOS Big Sur
- Browser (if applies): Firefox
- Version of supabase-js: n/a
- Version of Node.js: n/a

**Comment by enBonnet** [comment]
This issue is from another project, it's already reported https://github.com/supabase/supabase-ui-web/issues/5

**Comment by Dhaiwat10** [comment]
Awesome :)
