### ISSUE TITLE
Feature req: File upload input area

### ISSUE THREAD

**Issue by Dhaiwat10** [supabase/ui#254]
# Feature request

A file upload component which also supports drag & drop. Something like this:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/39617427/127958560-67dd480d-bf9f-45bb-95bd-682b019ee654.png">

## Is your feature request related to a problem? Please describe.

The current library of input components doesn't include a file upload utility. I think this is a necessity.

## Describe the solution you'd like

Create this component and add it to the library. 😅 Happy to do it myself and chip in a PR.

## Describe alternatives you've considered

n/a

## Additional context

n/a

**Comment by MildTomato** [comment]
@Dhaiwat10 go for it 👍 

Might want to check out `./src/components/upload` as it was already started a while back.
needs finishing

**Comment by Dhaiwat10** [comment]
Awesome

**Comment by Dhaiwat10** [comment]
@MildTomato were you able to have a quick look at the PR^ ?

**Comment by MildTomato** [comment]
Will look today 😄 @Dhaiwat10

**Comment by MildTomato** [comment]
### Supabase UI is being deprecated.

As part of that, we are closing issues in this repo that are perhaps outdated.

If you'd like to still make an issue, you could consider making an issue for our package in our monorepo https://github.com/supabase/supabase/tree/master/packages/ui

---

We are moving the components to the main mono repo at [https://github.com/supabase/supabase](https://github.com/supabase/supabase).

The auth component has been moved to it's own repo and package. [https://github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).
