### ISSUE TITLE
[Auth] Typography.Link isn't keyboard-accessible due to missing href

### ISSUE THREAD

**Issue by mryechkin** [supabase/ui#256]
# Bug report

## Describe the bug

When navigating the forms in `Auth` with a keyboard, all anchor tags generated from `Typography.Link` aren't accessible, as the `href` attributed is not applied in the rendered element:

<img width="470" alt="Screen Shot 2021-08-03 at 2 00 54 PM" src="https://user-images.githubusercontent.com/5657181/128063804-ed7e88d1-7678-481d-8a7b-c49916e5a0ee.png">

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run any of the examples utilizing `Auth` component from `@supabase/ui` or the example code from `README`
2. Navigate through the form fields with a `Tab` key
3. Observe how all links are skipped over and can't be focused on when using a keyboard

## Expected behavior

Links should be focusable and accessible when using a keyboard.

This currently happens due to the `href` attribute not being applied, as the `Typography.Link` component in `Auth` only uses  `onClick`.

Adding `tabindex="0"` to the anchor links will enable keyboard focusing, while retaining the rest of the functionality. Though, I would argue that to maintain semantical correctness use cases like these should be handled by a `button` styled like a link.

## Screenshots

**Current behaviour:**

https://user-images.githubusercontent.com/5657181/128063212-ef0f9f37-ee2d-4496-b5d9-90444412197e.mov

**Expected behaviour:**

(with `tabindex="0"` added manually for demo purposes)

https://user-images.githubusercontent.com/5657181/128063256-70f0cb27-a185-48cb-b9a4-3435862d0648.mov

## System information

- OS: macOS Catalina (`10.15.7`)
- Browser: Chrome `92.0.4515.107`
- Version of supabase-js: `0.32.0`
- Version of Node.js: `15.10.0`

## Additional context

I'd be happy to submit a PR for this if there are no concerns with the proposed solution? Thank you

**Comment by MildTomato** [comment]
This might be slightly bizarre, but we could give an id to the various sections and then use them in the `<a>` tags.

for instance, the actual final <a> tag could have a href like this:
```html
<a href="#auth-sign-up">Don't have an account? Sign up</a>
```

**Comment by mryechkin** [comment]
Yeah I guess that would work as well. Just have to make sure to `preventDefault()` in the `onClick` handler then

**Comment by mryechkin** [comment]
@MildTomato any objections to me taking this one if you're good with that approach?

**Comment by MildTomato** [comment]
@mryechkin go for it 👍
