### ISSUE TITLE
Show Carousel in Supabase Cards

### ISSUE THREAD

**Issue by Nazeeh21** [supabase/ui#260]
# Feature request
Show Carousel in Supabase Cards for multiple images if the user wants to display Carousel in the Cards

## Is your feature request related to a problem? Please describe.

I want to display the Carousel in Supabase cards for my website.

## Describe the solution you'd like
Add a Carousel in Supabase Cards, if the images passed in the props are more than one. 

If the user wants to display the images in Cards as a Carousel instead of a single image, display carousel.

## Describe alternatives you've considered

I manually added a Carousel library. It would be great if it would be a **native feature** of Supabase cards.

## Additional context

Example screenshot

![image](https://user-images.githubusercontent.com/56908732/129240970-fdcf8db6-a087-4102-9513-4b2ee9f754d6.png)

**Comment by MildTomato** [comment]
Be good to hear what others think but I don't think we should support this in this library so it leaves it to whoever is using it to pick whatever they want to use for images/carousels.
My first thought is anyone using NextJS will probably want to use Next/Image, and I think even in Supabase we have a used a couple of different libraries depending on what we were trying to do - so I'm a bit weary of adding this in as we'll never really hit enough use cases.

Although, this is just my opinion - be good to hear others 😄

**Comment by MildTomato** [comment]
Closing this for now
