### ISSUE TITLE
InputNumber Icon wrong position

### ISSUE THREAD

**Issue by pmauchle** [supabase/ui#276]
# Bug report

## Describe the bug

The icon on the _InputNumber_ is not showing correctly. Compared to the Component _Input_ where it is correct.

## To Reproduce

https://codesandbox.io/s/supabase-ui-inputnumber-0ii5y?file=/src/App.js

## Screenshots

![image](https://user-images.githubusercontent.com/3627771/133670569-c2fcc41a-6b1c-482f-9761-4ab529d67467.png)

**Comment by vaibhav111tandon** [comment]
@MildTomato Can I pick this up?

**Comment by MildTomato** [comment]
@vaibhav111tandon go for it!
