### ISSUE TITLE
Checkbox unable to mark as checked via a prop

### ISSUE THREAD

**Issue by joshenlim** [supabase/ui#28]
# Bug report

I noticed that the Checkbox has no prop to mark it as checked or not:

![image](https://user-images.githubusercontent.com/19742402/103808139-74cd7000-5092-11eb-956f-f636374aa105.png)

We'll need to add a prop to mark the checkbox as checked, such as in the context of persistent data

e.g `<Checkbox checked={true} />`

**Comment by MildTomato** [comment]
should work now

you also don't need to add so much if you don't want.
`value` and `id` come from `label` if they don't exist.

```javascript
function example() {
  const [check, setCheck] = useState(true)

  function toggleCheckbox(e) {
    setCheck(!check)
    
    console.log(e) 
    // console log returns 
    // {name: "lonely-checkbox", id: "lonely-checkbox", value: "lonely-checkbox", checked: true}**
  }
  
 

  return (
    <Checkbox label="lonely checkbox" checked={check} onChange={toggleCheckbox}/>
  )
}
  ```
