### ISSUE TITLE
Modal closes after mouse moving to overlay

### ISSUE THREAD

**Issue by asyncink** [supabase/ui#285]
# Bug report

Modal window from component <Modal /> closes after mouse moving to overlay

## Describe the bug

If user starts the click inside the modal content and moves the pointer outside the content area to the overlay area, then it behaves like the click was fired on the overlay area and the modal window closes.

## To Reproduce

1. Go to https://ui.supabase.com/components/modal
2. Click on 'Open Modal'
3. Press mouse button inside the content area of the modal, move pointer outside to the overlay and release the mouse button
4. Modal closes

## Expected behavior

Modal window should not close if the mouse pointer movement starts inside the content area. Typically that is done with the check of target event nodes

**Comment by MildTomato** [comment]
I think this is because the docs are out of date, the newer Modal probably doesn't behave like this.

Will investigate though 👍

**Comment by MildTomato** [comment]
### Supabase UI is being deprecated.

As part of that, we are closing issues in this repo that are perhaps outdated.

If you'd like to still make an issue, you could consider making an issue for our package in our monorepo https://github.com/supabase/supabase/tree/master/packages/ui

---

We are moving the components to the main mono repo at [https://github.com/supabase/supabase](https://github.com/supabase/supabase).

The auth component has been moved to it's own repo and package. [https://github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).
