### ISSUE TITLE
Default messages in english

### ISSUE THREAD

**Issue by brusacco** [supabase/ui#290]
# Feature request

Currently, the messages are hardcoded in English, like "Sign in with magic link", and it's no way to change them.

## Describe the solution you'd like

Add additional props to the component, to handle all those currently hardcoded texts, like:

signMagicLinkText="Sign in with magic link now!"

Thanks.

**Comment by MildTomato** [comment]
This looks like a duplication of https://github.com/supabase/ui/issues/261.
I'm going to close this is favour of #261.
