### ISSUE TITLE
Make Auth.UserContextProvider expose the 3 states of user data: unknown, known absent, and known present

### ISSUE THREAD

**Issue by aicushman** [supabase/ui#291]
# Feature request

## Is your feature request related to a problem? Please describe.

Not sure if this is a bug report or a feature request. Here's the problem:

The Auth.useUser hook often (always?) returns null immediately, no matter what. This makes Auth.useUser hard to use for client-side redirects.

Here's an example of something you might want to do: redirecting unauthorized users.

```jsx
const RedirectIfNotAuthorized(props:{permissions:'canSeeScreen'}) => {
	const user = Auth.useUser()
	if (!user) {
		//redirect
	}
	if (user.permissions != props.permissions) {
		//redirect
	}
	else return <MyCoolComponent/>
}
```

This is not currently possible. Auth.useUser() will always return null, triggering the first condition and causing an immediate redirect. Whether or not we have a user in localStorage, the redirect will fire.

Here's another pattern folks might want to use: showing a loading screen until we can redirect to login or display the content.

```jsx
const LoadingScreenOrContentOrRedirect() => {
	const user = Auth.useUser()

	if (waitingToKnowIfUserIsLoggedIn) {
		return <MyCoolLoadingScreen/>
	}

	if (userIsNotLoggedIn) {
		//redirect to login
	}
	else return <MyCoolComponent/>
}
```

This also does not work.  If using Auth.useUser(), the `waitingToKnowIfUserIsLoggedIn` and `userIsNotLoggedIn` states are both represented with the value `null` . If there's no user logged in, they'll be looking at my cool loading screen forever and never get redirected.

## Describe the solution you'd like
I've already fixed it for myself, [like so.](https://github.com/aicushman/ui/commit/3c4e837342f13e4c6c31feecf1d0a0b0eaf054b7) Basically, initializing the `user` and `session` variables in the UserContextProvider function as `undefined` instead of `null` handles everything. Then you can just use ` session === undefined` as the loading state.

More generally, though: when I call `Auth.useUser`, I would like it to initially report a Loading/Unknown state, and resolve this state to either Known Missing, or Known Present.

If there's some better way of achieving this, all the better.

## Describe alternatives you've considered

I'm not aware of a reasonable alternative. I have seen people invoking useUser with a timeout so that the function has time to fetch user data if it is present.

**Comment by chipilov** [comment]
IMHO, this cannot be reliably solved in the UI library without changes in the underlying GoTrue.js client.

I think this is the relevant bug which first needs to be fixed in the GoTrue.js library: https://github.com/supabase/gotrue-js/issues/143

**Comment by MildTomato** [comment]
This is interesting - since we have complete control over the provider we could probably have some more interesting and useful props like 'loading' perhaps.

having an undefined might be a nice compromise for now since it won't change it much and not break it for current users.

**Comment by MildTomato** [comment]
ps. this repo has been left stale for a while, i intend to get back to it this week :D

**Comment by MildTomato** [comment]
this is also related https://github.com/supabase/ui/pull/269
