### ISSUE TITLE
Input component with label prop does not set `for` attribute

### ISSUE THREAD

**Issue by Ziinc** [supabase/ui#310]
# Bug report
the `<Input label="From" />` does not correctly set the `for` attribute on the label.

Discovered this bug when attempting to select the input through the label with dom-testing-library, which gave this error:
```
  Found a label with the text of: From, however no form control was found associated to that label. 
  Make sure you're using the "for" attribute or "aria-labelledby" attribute correctly.
```

Checking the generated label tag gives the following:
```
              <div class="sbui-space-row sbui-space-x-2 sbui-formlayout__label-container-horizontal" >
                      <label class="sbui-formlayout__label">
                        From
                      </label>
                      <span class="sbui-formlayout__label-opt" id="undefined-optional">
                        UTC
                      </span>
                    </div>
                    <div class="sbui-formlayout__content-container-horizontal">
                      <div class="sbui-input-container">
                        <input
                          class="sbui-input sbui-input--tiny"
                          type="text"
                          value="2022-01-17T10:44:23.987Z"
                        />
                        <div class="sbui-space-row sbui-space-x-1 sbui-input-actions-container">
                          <span class="sbui-btn-container">
                            <button class="sbui-btn sbui-btn-secondary sbui-btn-container--shadow sbui-btn--tiny sbui-btn--text-align-center" title="Set" >
                              <span> Set </span>
                            </button>
                          </span>
                        </div>
```

As you can see, the `for` attribute on the `<label>` tag is not set.

You can also see the behaviour in the [docs](https://ui.supabase.io/components/input#input-labels) by inspecting the label

This issue would affect accessibility.

**Comment by MildTomato** [comment]
this is will be fixed in theming release

**Comment by MildTomato** [comment]
### Supabase UI is being deprecated.

As part of that, we are closing Pull Requests in this repo for now.

If you'd like to still make these changes, you could consider making these changes in https://github.com/supabase/supabase/tree/master/packages/ui

---

We are moving the components to the main mono repo at [https://github.com/supabase/supabase](https://github.com/supabase/supabase).

The auth component has been moved to it's own repo and package. [https://github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).
