### ISSUE TITLE
Popover component showClose icon overlaps with overlay elements

### ISSUE THREAD

**Issue by Ziinc** [supabase/ui#312]
Using the Popover component with `showClose` enabled results in overlap in elements

You can faintly see the overlap of the `X` icon with the input, this is because there is no padding set to the overlay.
<img width="392" alt="image" src="https://user-images.githubusercontent.com/22714384/150154549-0aeda1ae-39e4-4fe2-9029-f27e2cb37dc1.png">

Also, on a separate note, seems like we will need to set the padding of the overlay contents directly? I saw that from the stories, just want to check that it is the ideal way to set the internal padding, as it would mean wrapping it with an unnecessary div.

**Comment by egor-romanov** [comment]
Closing the issue due to it being inactive and/or outdated. There's a large chance that this issue has been solved since, I can't find any place where it can be reproduced.
Please do not hesitate to reopen and if it is still relevant
