### ISSUE TITLE
Auth email confirmation message will not display

### ISSUE THREAD

**Issue by alexchenhz** [supabase/ui#319]
# Bug report

## Describe the bug

When use signs up, the message "Check your email for the confirmation link." does not display. 

This is caused by the code [here](https://github.com/supabase/ui/blob/461bea21c31cabe5a5ce87045e71b7c773d912ee/src/components/Auth/Auth.tsx#L327-L339)

According to the [docs](https://supabase.com/docs/reference/javascript/auth-signup), `supabase.auth.signUp()` does not return an object with the parameter `data`, instead,

![image](https://user-images.githubusercontent.com/10442542/151216881-5320dc32-b701-4bd4-a977-fef9d29a4edb.png)

Thus, should check instead that a user object was returned, not `signUpData`.

## To Reproduce

Attempt to sign up a new user using the `Auth` component.

## Expected behavior

The message is expected to display after sign up has been submitted. 

## Additional context

Related to changes made for this issue: https://github.com/supabase/ui/issues/73

**Comment by flavrwebdev** [comment]
+1 on this. I thought I was doing something wrong with tracking the view events but this is caused exactly how Alex @alexchenhz has explained.

This currently causes quite a big issue with the user sign up flow as no feedback is provided to the user at all.

**Comment by alexchenhz** [comment]
Created a PR: https://github.com/supabase/ui/pull/320
