### ISSUE TITLE
Move Auth Component to Supabase Auth Helpers

### ISSUE THREAD

**Issue by MildTomato** [supabase/ui#328]
# Feature request

## Describe the solution you'd like

Move the Auth component to the Supabase Auth Helpers library in Supabase community.

https://github.com/supabase-community/supabase-auth-helpers/issues/31

Remove the Auth component and exports from this library. 

## Describe alternatives you've considered

Considered hosting the pre built UI in it's own repo, but it's probably more straightforward to add it to the auth helpers library

**Comment by kaspnilsson** [comment]
Hi,

Please do consider bundle size issues when making this change. I use the helpers but not these UI components, but the way they've been included in the library increases my bundle size massively anyway.

**Comment by MildTomato** [comment]
Yep, this bundle size is pretty big, we won't be just moving the auth component over, we will rework how they work so they don't have any dependencies from @supabase/ui.

**Comment by MildTomato** [comment]
The auth component has been moved to it's own repo and package.

[github.com/supabase-community/auth-ui](github.com/supabase-community/auth-ui).
You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).
