### ISSUE TITLE
Fix Icon position with InputNumber.

### ISSUE THREAD

**Issue by yo9e5h** [supabase/ui#332]
# Bug report

The Icon is not aligned with input field.

## Expected behavior

Icon should align with input field in InputNumber.

## Screenshots

<img width="426" alt="Screenshot 2022-03-09 at 12 14 27" src="https://user-images.githubusercontent.com/11131787/157387797-c5ea97be-f5c8-4721-bed0-e0ce20d00aa8.png">

**Comment by MildTomato** [comment]
This is possibly fixed in the pre release versions
