### ISSUE TITLE
Input.TextArea overflow scroll bars need to be adjusted to match theme

### ISSUE THREAD

**Issue by Ziinc** [supabase/ui#334]
<img width="471" alt="image" src="https://user-images.githubusercontent.com/22714384/158570292-f034eebe-5109-4a79-8d8d-3435d718a1bc.png">

**Comment by Ziinc** [comment]
Also, copy button overlaps with the scroll bar, pehaps can default to using slim scrollbars

**Comment by Hallidayo** [comment]
@Ziinc - What browser/device are using?

I am running Chrome 99.0.4844.74 on MacOS and I see the following:

<img width="82" alt="Screenshot 2022-03-22 at 12 56 59" src="https://user-images.githubusercontent.com/22655069/159487377-2fb29271-9e34-478e-854a-afeb4ec85415.png">

**Comment by MildTomato** [comment]
The scrollable tabs are also doing this, probably something browser-specific we've forgotten about.

I think the best way to treat scroll bars is to just use the default browser scroll bars, the major browsers all have good implementations.

I tried adding custom scrollbars based on light and dark themes and it seems to not support transparency either, so the default browser scrollbars always ended up looking and feeling better.

**Comment by egor-romanov** [comment]
Closing the issue, as it seems like the original issue has been partially resolved. I'd prefer someone to create a new issue with a fresh description if it's still an issue.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.

Looks like we use custom on scroll and browser default on hover, looks like this is what is expected from the thread
