### ISSUE TITLE
Buttons with Icons alignment

### ISSUE THREAD

**Issue by Hallidayo** [supabase/ui#336]
# Improve documentation

## Link 

[Button Using Icons](https://ui.supabase.io/components/button#using-icons)

## Describe the problem

The buttons in the example code block are not aligned with the button to right slightly down a bit:

<img width="689" alt="Screenshot 2022-03-22 at 12 21 38" src="https://user-images.githubusercontent.com/22655069/159480903-ad7e9bcf-c25d-4901-9b39-cc47307bdaf5.png">

## Describe the improvement

The two buttons in my view should be aligned on the same line.

**Comment by MildTomato** [comment]
They should be inside a div with flex box usually.
Not sure why they are misaligned in the first place though.

The Button used to have a container `<div>` around it before, and it's been removed in the pre release versions, so it might not behave like this anymore.

```jsx
<div className="flex items-center">
  <Button>Button</Button>
  <Button>Button</Button>
</div>
```

**Comment by Hallidayo** [comment]
@MildTomato - I've just created a [pull request](https://github.com/supabase/supabase-ui-web/pull/50). Would have been sooner if Github had not gone down 😂

**Comment by Devkant21** [comment]
Is this issue solved yet? If not can i take it up and work on it?

**Comment by Hallidayo** [comment]
@Devkant21 Should be solved in the pr 👍

**Comment by Devkant21** [comment]
> @Devkant21 Should be solved in the pr 👍

ok

**Comment by MildTomato** [comment]
### Supabase UI is being deprecated.

As part of that, we are closing Pull Requests in this repo for now.

If you'd like to still make these changes, you could consider making these changes in https://github.com/supabase/supabase/tree/master/packages/ui

---

We are moving the components to the main mono repo at [https://github.com/supabase/supabase](https://github.com/supabase/supabase).

The auth component has been moved to it's own repo and package. [https://github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).
