### ISSUE TITLE
Badge component needs a `className` prop for styling of wrapper element

### ISSUE THREAD

**Issue by Ziinc** [supabase/ui#339]
<img width="324" alt="image" src="https://user-images.githubusercontent.com/22714384/159717760-d9d90d6c-1056-4017-a968-8a36f38b9554.png">

right now not easy to customize the badge component.

Also needed for styling the inner contents of the badge, otherwise would have to wrap the child in additional tags.

**Comment by MildTomato** [comment]
### Supabase UI is being deprecated.

As part of that, we are closing Pull Requests in this repo for now.

If you'd like to still make these changes, you could consider making these changes in https://github.com/supabase/supabase/tree/master/packages/ui

---

We are moving the components to the main mono repo at [https://github.com/supabase/supabase](https://github.com/supabase/supabase).

The auth component has been moved to it's own repo and package. [https://github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).
