### ISSUE TITLE
Alert: width of children is not maximized

### ISSUE THREAD

**Issue by Ziinc** [supabase/ui#343]
<img width="728" alt="image" src="https://user-images.githubusercontent.com/22714384/162743925-c5852d9b-2809-4131-b845-2b1656bf18cf.png">

the size of the Alert title seems to set the inner children's width

**Comment by asantesylvesterkwame** [comment]
Please Assign me to this task!

**Comment by MildTomato** [comment]
### Supabase UI is being deprecated.

As part of that, we are closing Pull Requests in this repo for now.

If you'd like to still make these changes, you could consider making these changes in https://github.com/supabase/supabase/tree/master/packages/ui

---

We are moving the components to the main mono repo at [https://github.com/supabase/supabase](https://github.com/supabase/supabase).

The auth component has been moved to it's own repo and package. [https://github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).
