### ISSUE TITLE
Form does not reset after failed login/signup

### ISSUE THREAD

**Issue by mozeryansky** [supabase/ui#345]
# Bug report

## Describe the bug

When I cause an auth failure the form will show a spinner on the button and the error message, but the button stays disabled and I can't submit the form again.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Enter an unregistered email/password
2. Press 'Sign In'

## Expected behavior

Enable the button after resetting the form.

## Screenshots

<img width="668" alt="Screen Shot 2022-04-16 at 6 49 22 PM" src="https://user-images.githubusercontent.com/3287719/163694612-83873f5f-7bc2-44f6-9a58-9a96ef3eb02b.png">

## System information

- OS: macOS
- Version of supabase-js: 1.33.3
- Version of Node.js: 14.18.1

**Comment by Hallidayo** [comment]
@mozeryansky - Do you get any errors in the console? I can not seem to replicate:


https://user-images.githubusercontent.com/22655069/164065640-8c396968-d52d-4c4b-beb6-3513122c9da0.mov

**Comment by mozeryansky** [comment]
The only log is the failed login attempt:
```
POST https://jfpobqybpivejuojlnsj.supabase.co/auth/v1/token?grant_type=password [400 Bad Request 257ms]
```

Here I see loading is set true, but it is not set to false after the requests come back:
https://github.com/supabase/ui/blob/c280fa175f2327a2c823951843f7e5b30dd6b9b4/src/components/Auth/Auth.tsx#L312-L326

Should that code call this function instead?
https://github.com/supabase/ui/blob/c280fa175f2327a2c823951843f7e5b30dd6b9b4/src/components/Auth/Auth.tsx#L217-L225

Although I'm not sure how yours is working and mine is not. I tried Firefox and Chrome. Seeing that loading is set false on mount I wonder if your sample is redirecting? Here is how I use the components:
```
return <>
    <div style={{ width: '50%', margin: 'auto' }}>
      <SupabaseAuth.UserContextProvider supabaseClient={supabaseClient}>
        <div>
          <SupabaseAuth supabaseClient={supabaseClient} />
        </div>
      </SupabaseAuth.UserContextProvider>
    </div>
  </>
```
And I have no redirects/re-mounts.

**Comment by mozeryansky** [comment]
I tried setting up a dev environment but I realized I'm not using React 18. I couldn't follow the linking instructions in `development.md` since there are breaking changes for React 18. I checked out an older version of my project using react 17 and the form does reset, so it must be a React 18 related issue.

**Comment by Hallidayo** [comment]
Yeah I think this is related to React 18. I've just updated `react react-dom` to their latest versions on my test project. After updating I seem to be getting the same as what you have experienced in your opening post:


https://user-images.githubusercontent.com/22655069/164188462-b9bb561a-3b7b-4f5d-8834-482011a39bb5.mov

In the example above I was just using the example in the docs:

```
import { Auth, Typography, Button } from "@supabase/ui";
import { createClient } from "@supabase/supabase-js";

const supabaseUrl = 
const supabaseAnonKey = 

const supabase = createClient(supabaseUrl, supabaseAnonKey);

const Container = (props) => {
  const { user } = Auth.useUser();
  if (user)
    return (
      <div className="m-5 p-5">
        <Typography.Text>Signed in: {user.email}</Typography.Text>
        <Button block onClick={() => props.supabaseClient.auth.signOut()}>
          Sign out
        </Button>
      </div>
    );
  return props.children;
};

export default function AuthBasic() {
  return (
    <Auth.UserContextProvider supabaseClient={supabase}>
      <div className="m-10 w-72 flex items-center justify-center">
        <Container supabaseClient={supabase}>
          <Auth supabaseClient={supabase} />
        </Container>
      </div>
    </Auth.UserContextProvider>
  );
}
```

**Comment by Aldo111** [comment]
Is there a better way to handle this in react 18?

**Comment by mozeryansky** [comment]
> Is there a better way to handle this in react 18?

https://github.com/supabase/ui/issues/350

No, I intend to make my own login form. The current form is nice but I don't want the UI just the functionality, it'd be good if they exposed something like `useAuthForm()` and I can define all the UI myself.

**Comment by MildTomato** [comment]
@mozeryansky this might be handy https://github.com/supabase-community/supabase-auth-helpers

**Comment by MildTomato** [comment]
The auth component has been moved to it's own repo and package.
[github.com/supabase-community/auth-ui](github.com/supabase-community/auth-ui).
You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).

Thanks for all the comments and suggestions so far.
If this is still an issue, please open a new issue in the new repo.
