### ISSUE TITLE
Button type link doesn't apply style color

### ISSUE THREAD

**Issue by phamhieu** [supabase/ui#35]
# Bug report

## Describe the bug

```js
<Button onClick={onClick} type="link" size="small" style={{ color: '#bbbbbb' }}>
  Link Button
</Button>
```

color doesn't apply to button text. It always has default white color.

**Comment by MildTomato** [comment]
it looks like tailwind utilities in /app is overriding  the `<span>` inside `<Button>`

will have a look at workarounds

**Comment by MildTomato** [comment]
![Screenshot 2021-01-07 at 20 15 05](https://user-images.githubusercontent.com/8291514/103891598-16050680-5125-11eb-8333-b91cf2d9f6d4.png)

need to change this from `font-color` to `color` in `/app`

we should probably keep this stuff in style.scss for now,  but we can move the reset/modern-normalize type of css to `ui` later.

**Comment by MildTomato** [comment]
fixed in `/app` repo
