### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by mozeryansky** [supabase/ui#350]
# Bug report

## Describe the bug

```
$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @supabase/ui@0.36.5
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!   peer react@"^18.0.0" from @testing-library/react@13.1.1
npm ERR!   node_modules/@testing-library/react
npm ERR!     dev @testing-library/react@"^13.1.1" from the root project
npm ERR!   5 more (next, react-dom, react-query, styled-jsx, use-sync-external-store)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1 || ^17.0.1" from @supabase/ui@0.36.5
npm ERR! node_modules/@supabase/ui
npm ERR!   @supabase/ui@"^0.36.5" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^16.13.1 || ^17.0.1" from @supabase/ui@0.36.5
npm ERR!   node_modules/@supabase/ui
npm ERR!     @supabase/ui@"^0.36.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `npm install react@latest @supabase/ui@latest`

## Expected behavior

Supabase UI to be compatible with React 18

**Comment by mozeryansky** [comment]
I am able to use `--force` and my project works fine. Currently, I am only using the Auth component.

**Comment by MildTomato** [comment]
Just a heads up, we are moving the Auth component to https://github.com/supabase-community/auth-ui soon

**Comment by eebbann** [comment]
add --force when installing dependencies it works

**Comment by willopez** [comment]
@MildTomato is there a plan to support React 18?

**Comment by MildTomato** [comment]
@willopez there is no plan now, as we've decided to move all the supabase ui components to our monorepo.
We will then only really be supporting the react versions being used in our monorepo.

**Comment by MildTomato** [comment]
### Supabase UI is being deprecated.

As part of that, we are closing issues in this repo that are perhaps outdated.

If you'd like to still make an issue, you could consider making an issue for our package in our monorepo https://github.com/supabase/supabase/tree/master/packages/ui

---

We are moving the components to the main mono repo at [https://github.com/supabase/supabase](https://github.com/supabase/supabase).

The auth component has been moved to it's own repo and package. [https://github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).
