### ISSUE TITLE
Google OAuth Reports Branding Issue

### ISSUE THREAD

**Issue by dyaffe** [supabase/ui#356]
# Bug report

## Describe the bug

During OAuth approval, Google reported the following to us:

You need to update the Google sign-in button on your project’s homepage so that it complies with the [Google sign-in branding guidelines](https://google.com/url?&q=http%3A%2F%2Fdevelopers.google.com%2Fidentity%2Fbranding-guidelines%23top_of_page). Please see attached screenshots for reference: 

![Screenshot 2022-05-30 4 01 10 PM](https://user-images.githubusercontent.com/8095717/171210530-23dad770-7abb-492a-ac17-a872c0853c1e.png)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create OAuth with Google
2. Note the button color doesn't comply with Google branding requirements.
3. Set socialColors to false
4. Notice it still doesn't comply.

## Expected behavior

I would expect that the button color and branding would automatically comply with the [Google sign-in branding guidelines](https://google.com/url?&q=http%3A%2F%2Fdevelopers.google.com%2Fidentity%2Fbranding-guidelines%23top_of_page).

## Screenshots

Here are the two options for branding colors currently (note they don't comply).

socialColors = True
![Screenshot 2022-05-30 4 01 10 PM](https://user-images.githubusercontent.com/8095717/171211244-783ae730-ce05-441d-841e-de432a4eed61.png)

socialColors = False
<img width="320" alt="supabase-ui__social-colors__false" src="https://user-images.githubusercontent.com/8095717/171211773-92cd95fc-ab28-41e0-90ea-7e2d9c33606c.PNG">

## System information

Happens across all machines

## Additional context

N/A

**Comment by MildTomato** [comment]
The auth component has been moved to it's own repo and package.
[github.com/supabase-community/auth-ui](github.com/supabase-community/auth-ui).
You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).

This issue has been fixed in the new repo.
