### ISSUE TITLE
Button to support Ref forwarding

### ISSUE THREAD

**Issue by phamhieu** [supabase/ui#36]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently Button component doesn't support `ref` prop. 

https://reactjs.org/docs/forwarding-refs.html

```js
<Button ref={button} type="secondary" size="tiny" onClick={onClick}>
    Button with ref
</Button>
```

**Comment by MildTomato** [comment]
@phamhieu is this only used by a Tooltip?

**Comment by MildTomato** [comment]
I'll add it in anyway 😌

**Comment by MildTomato** [comment]
just noting this here in case we encounter any problems - react docs make a point about using forwarding refs in component libraries.
https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers

**Comment by phamhieu** [comment]
The code is missing `React.forwardRef`

<img width="592" alt="Screenshot 2021-01-08 at 2 44 26 PM" src="https://user-images.githubusercontent.com/689843/103983329-04bd0800-51c0-11eb-98b9-cb4618344a91.png">

**Comment by MildTomato** [comment]
ahh sorry! i'll change it :)

**Comment by MildTomato** [comment]
Having trouble fixing this.

made an attempt on branch `fix/button-ref-fix`

**Comment by MildTomato** [comment]
@phamhieu is this working ok ? 😄

**Comment by phamhieu** [comment]
yes, it works now
