### ISSUE TITLE
Only allow magic link sign in with the Auth component

### ISSUE THREAD

**Issue by nahtnam** [supabase/ui#360]
# Feature request

## Is your feature request related to a problem? Please describe.

I would like to only allow the use of magic link (no password sign in)

## Describe the solution you'd like

Maybe a flag `noPasswordAuth`?

## Describe alternatives you've considered

Tried this:

```
magicLink
view="magic_link"
```

However there's still a link to go to the sign_in view

## Additional context

I personally don't want to store passwords, be responsible for passwords,  or allow for passwords

**Comment by MildTomato** [comment]
Auth component is being deprecated.
It will be replaced with [Auth UI](https://github.com/supabase-community/auth-ui)

I have been working on updating the new component to work with child components for exactly this use case.



The current component your using may be able to use <Auth.MagicLink/>, although I haven't tried it myself to be honest.

**Comment by nahtnam** [comment]
Ooo very nice, I'll give that a shot. I noticed that it's written in typescript but it seems like types arent exported?

```
Could not find a declaration file for module '@supabase/auth-ui-react'. '/node_modules/@supabase/auth-ui-react/dist/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/supabase__auth-ui-react` if it exists or add a new declaration (.d.ts) file containing `declare module '@supabase/auth-ui-react';`ts(7016)
```

Any ideas on what could be going on?

**Comment by MildTomato** [comment]
its prerelease currently, i think it's pending to be done

**Comment by MildTomato** [comment]
if you fancy adding that in feel free to pull request some changes if you like. I won't have time to work on this until next week

**Comment by MildTomato** [comment]
expect breaking changes btw. especially in regards to the theme/customization.
I'll probably change it so you have to explicitly import the theme into the component.

something like...

```jsx
import Auth, { themes } from '@supabase/auth-ui-react'

<Auth appearance={{theme: themes.supabase }} />
```

**Comment by MildTomato** [comment]
The auth component has been moved to it's own repo and package.
[github.com/supabase-community/auth-ui](github.com/supabase-community/auth-ui).
You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).
