### ISSUE TITLE
Modal not showing up

### ISSUE THREAD

**Issue by Perfecto-always** [supabase/ui#361]
# Bug report

## Describe the bug

Modal created using the example docs is not showing up when opened

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Add a toggle function to a button to control the modal opening
2. Click on the button

## Expected behavior

The modal should be open and should stay open

## Screenshots

Here is what I see when I'm debugging:
![image](https://user-images.githubusercontent.com/74700079/177125211-aaad2efe-52ff-4d68-9f6e-d6aa1116f757.png)
The images shows that the element is created and appended to the DOM but also is quickly removed from the same.

## System information

- OS: Codespaces(Linux)
- Chrome
- Version of Supabase/ui: "0.36.5"

## Additional context

Here is the codesandbox with the issue: [Modal not showing up](https://codesandbox.io/s/charming-dirac-gvn7vv?file=/src/App.js)

**Comment by Perfecto-always** [comment]
@Hallidayo could this be because of `radix` library?

**Comment by MildTomato** [comment]
### Supabase UI is being deprecated.

As part of that, we are closing issues in this repo that are perhaps outdated.

If you'd like to still make an issue, you could consider making an issue for our package in our monorepo https://github.com/supabase/supabase/tree/master/packages/ui

---

We are moving the components to the main mono repo at [https://github.com/supabase/supabase](https://github.com/supabase/supabase).

The auth component has been moved to it's own repo and package. [https://github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).
