### ISSUE TITLE
Svelte Component please! 🙏🙏🙏

### ISSUE THREAD

**Issue by ofeenee** [supabase/ui#362]
# Feature request

## Is your feature request related to a problem? Please describe.

A clear and concise description of what you want and what your use case is.

**Comment by Isaiah-Hamilton** [comment]
@ofeenee is this some what you are looking for? https://github.com/supabase-community/supabase-ui-svelte

**Comment by MildTomato** [comment]
The auth component has been moved to it's own repo and package.

[github.com/supabase-community/auth-ui](github.com/supabase-community/auth-ui).
You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).

It would be great if maybe we can start development on a svelte version in there.

I'm closing this for now, but feel free to make issues in the new repo.
