### ISSUE TITLE
Supabase Auth UI does not function in TypeScript

### ISSUE THREAD

**Issue by CompeyDev** [supabase/ui#372]
# Bug report

## Describe the bug
The examples given on the page https://ui.supabase.io/components/auth do not seem to work (in TypeScript with the latest Next.js). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```tsx
export default function AuthBasic() {
  return (
    <Auth.UserContextProvider supabaseClient={supabase}>
      <Container supabaseClient={supabase}>
        <Auth onlyThirdPartyProviders={true} supabaseClient={supabase} providers={['google', 'facebook', 'github']} />
      </Container>
    </Auth.UserContextProvider>
  )
}

```

## Expected behavior

The given code would compile with no errors.

## Screenshots

![image](https://user-images.githubusercontent.com/74418041/185800769-2a1ee309-0766-41fc-8819-c9963226e472.png)

## System information

- OS: Windows
- Version of supabase-js: 2.0.0-rc.4
- Version of Node.js: 16.16.0

## Additional information

While installing the UI package, A bunch of errors with peer dependencies occurred:
![image](https://user-images.githubusercontent.com/74418041/185800907-180f58bc-c2aa-412a-b5b2-01c2e4fb1c3d.png)

**Comment by CompeyDev** [comment]
More errors that seem to occur with the package
![image](https://user-images.githubusercontent.com/74418041/185875043-507fce62-5cd3-4533-b01d-49bc7e99f8e9.png)

This occurs within the package itself.

**Comment by CompeyDev** [comment]
Sorry for accidentally closing the issue! 😅

**Comment by phongplus** [comment]
remove  <Auth.UserContextProvider supabaseClient={supabase}> and will work.

**Comment by MildTomato** [comment]
This component is being deprecated.

Would it be ok to please refer to https://github.com/supabase-community/auth-ui

It is a new NPM package, so please use the new package 😄

**Comment by CompeyDev** [comment]
> remove <Auth.UserContextProvider supabaseClient={supabase}> and will work.

It would not.

**Comment by CompeyDev** [comment]
> This component is being deprecated.
> 
> Would it be ok to please refer to https://github.com/supabase-community/auth-ui
> 
> It is a new NPM package, so please use the new package 😄

Sure, thanks for the help :)

Will let you know if I'm running into more issues.

**Comment by MildTomato** [comment]
I'm going to close this issue for now since we have moved this component to https://github.com/supabase-community/auth-ui
