### ISSUE TITLE
Supabase UI Modal container collapse / positioning issue

### ISSUE THREAD

**Issue by brianaderer** [supabase/ui#373]
# Bug report

`.sbui-modal-container` is not being added to immediate parent of `.sbui-modal `causing container collapse. It was working and then all of a sudden stopped on a server restart, rolling back changes does not help. Manually adding `.sbui-modal-container` to the highlighted div in the photo fixes the layout issue, but the class is not being added by the Modal function for some reason.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

I'm using NextJS with typescript. I'm not sure what's causing it aside from the missing class, so I can't be more specific about steps to reproduce

## Expected behavior

The immediate parent of the `.sbui-modal` div (shown in images) needs a class that prevents it from collapsing, it looks like the added class should be `.sbui-modal.container`

## Screenshots

![Screenshot 2022-09-01 113435](https://user-images.githubusercontent.com/24856852/187986295-657570b5-2d66-4520-9aae-042bd778e403.png)
![Screenshot 2022-09-01 113508](https://user-images.githubusercontent.com/24856852/187986299-78f1e1a6-8c6f-4ec1-9933-04ecdf7eb5b8.png)
![Screenshot 2022-09-01 113557](https://user-images.githubusercontent.com/24856852/187986303-d40a1f17-2f6f-4543-bfea-517b0e3ad6a1.png)
![Screenshot 2022-09-01 113813](https://user-images.githubusercontent.com/24856852/187986307-dbf51245-b15c-4c08-b970-4fef66227b86.png)

## System information

- OS: [windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 1.35.4]
-  Version of supabase/ui [e.g. 0.36.5]
- Version of Node.js: [e.g. 16.13.2]

**Comment by brianaderer** [comment]
I am working around for now by targeting that div using a child selector and manually adding all the properties of .sbui-modal-container but this is messy, and I do believe the behavior is a bug

**Comment by lucky-chap** [comment]
@brianaderer this is not related to the post. But just want to know if this project is discontinued, because it seems there hasn't been any activity for over a month now

**Comment by MildTomato** [comment]
### Supabase UI is moving.

We are moving the components to the main mono repo at [github.com/supabase/supabase](github.com/supabase/supabase).

Closing this issue as it's been solved in the monorepo.
