### ISSUE TITLE
LinkedIn Icon not coming in Auth Component

### ISSUE THREAD

**Issue by sahilpopli** [supabase/ui#375]
# Bug report

## Describe the bug
I have used Auth as given in one of your GitHub examples, everything working like water flows except  the Linkedin icon is missing.

This is the code.
```
import { Auth, Card, Typography, Space, Button, Icon, ThemeSupa  } from '@supabase/ui'
--
<Auth
            supabaseClient={supabase}
            providers={['google', 'linkedin', 'github']}
            view={authView}
            appearance={{ theme: ThemeSupa }}
            socialLayout="horizontal"
            socialButtonSize="xlarge"
/>

// and my packeage.json

 "@supabase/auth-helpers-nextjs": "^0.2.8",
 "@supabase/supabase-js": "^1.35.6",
 "@supabase/ui": "^0.36.5",


```

I checked at this repo where there is no linkedin icon data - https://github.com/supabase/auth-elements/blob/master/src/components/Auth/Icons.tsx

How can I add this without breaking stuff? 

## Screenshots

![image](https://user-images.githubusercontent.com/1723958/190880728-3819fb5a-b1ff-42b0-98ee-3f53a14ed0e2.png)

## System information

- OS:  Windows
- Browser (if applies)   chrome

**Comment by sahilpopli** [comment]
I added this in the dependency file to check,  under Auth component > icons file

```
const linkedin = () => jsxRuntime.jsx("svg", Object.assign({
  width: size,
  "aria-hidden": "true",
  focusable: "false",
  "data-prefix": "fab",
  "data-icon": "linkedin",
  className: "svg-inline--fa fa-linkedin fa-w-16",
  role: "img",
  xmlns: "http://www.w3.org/2000/svg",
  viewBox: "0 0 448 512"
}, {
  children: jsxRuntime.jsx("path", {
    fill: "currentColor",
    d: "M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z"
  }, void 0)
}), void 0);
```

But its invoking Hyderation error.

![image](https://user-images.githubusercontent.com/1723958/190881167-39e68a59-bc4c-4039-9d2f-551c381e05e9.png)

**Comment by MildTomato** [comment]
Hey @sahilpopli - perhaps this has already been fixed in the new version of Auth UI.

The auth ui component has moved to [github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui)
The new NPM package is [@supabase/auth-ui-react](https://www.npmjs.com/package/@supabase/auth-ui-react)

You can read the [new docs for it here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).
