### ISSUE TITLE
Auth component need captcha support

### ISSUE THREAD

**Issue by chwan97** [supabase/ui#377]
When I turn on hCaptcha feature in dashboard, system always return me  "request disallowed"

Auth component need captcha support, or give a way that users can implement  it by themself.

**Comment by MildTomato** [comment]
Supabase UI is being deprecated.
We are moving the components to the main mono repo at [github.com/supabase/supabase](https://github.com/supabase/ui/blob/master/github.com/supabase/supabase).

The auth component has been moved to it's own repo and package. [github.com/supabase-community/auth-ui](https://github.com/supabase/ui/blob/master/github.com/supabase-community/auth-ui). You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).

Please reopen your issue there.
Thanks.

**Comment by franz-josef-kaiser** [comment]
@MildTomato The links to [github.com/supabase-community/auth-ui](https://github.com/supabase/ui/blob/master/github.com/supabase-community/auth-ui) and [github.com/supabase/supabase](https://github.com/supabase/ui/blob/master/github.com/supabase/supabase) is a 404.
