### ISSUE TITLE
SidePanel is not available locally.

### ISSUE THREAD

**Issue by ru88s** [supabase/ui#379]
SidePanel is not available locally.
"next": "^13.0.1",
"@supabase/ui": "^0.36.5",

It works in production.

**Comment by MildTomato** [comment]
## Supabase UI is being deprecated. 

We are moving the components to the main mono repo at [https://github.com/supabase/supabase](https://github.com/supabase/supabase).

The auth component has been moved to it's own repo and package.
[github.com/supabase/auth-ui](https://github.com/supabase/auth-ui).
You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).

**Comment by ru88s** [comment]
@MildTomato 
Thank you.
Hasn't SidePanel been done since?
https://github.com/supabase/auth-ui/tree/main/packages/react/src/components/UI

**Comment by ru88s** [comment]
Is it this?
How do I import?
https://github.com/supabase/supabase/tree/master/packages/ui/src/components

**Comment by ru88s** [comment]
`reactStrictMode: false`.
now works locally as well.

**Comment by MildTomato** [comment]
We don't use this package anymore in supabase so I'm not sure.
We moved all the components into our mono repo and stopped publishing the npm package.

To be honest, if there is enough interest we can put some real effort into making this into a real tailwind UI library, but for now things kept changing on our front end and we felt it was easier to not have it as an npm package so we could develop faster.
