### ISSUE TITLE
Badge w/ dot and color has square background of badge

### ISSUE THREAD

**Issue by plondon** [supabase/ui#380]
# Bug report
When setting `dot` prop && color of a badge, the result is an awkward square background around dot.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Add Badge
2. set dot prop to true w/ any color

```
<Badge color='green' dot>Hello World</Badge>
```

## Expected behavior

Maybe the background should have a rounded radius? Or not exist at all.

## Screenshots

<img width="330" alt="Screen Shot 2022-11-03 at 9 57 38 AM" src="https://user-images.githubusercontent.com/5640772/199740203-7973a0bd-793e-49cd-9892-9b46c0e6decb.png">

## System information

- OS: [e.g. macOS]
- Browser (if applies) [e.g. chrome, safari]
- supabase/ui latest

## Additional context
The docs look ok because no color is set so `sbui-badge--[red, green, yellow, etc...]` is undefined.

<img width="1096" alt="Screen Shot 2022-11-03 at 9 58 48 AM" src="https://user-images.githubusercontent.com/5640772/199740468-2b011321-0fca-4814-84c0-50f7cc5a3210.png">

**Comment by harshcut** [comment]
This is due to the `sbui-badge--${color}` being applied to the SVG, which gives the background color for the component wrapper.

```diff
- className={`${BadgeStyles[`sbui-badge-dot`]} ${
-   BadgeStyles[`sbui-badge--${color}`]
- }`}
+ className={`${BadgeStyles[`sbui-badge-dot`]}`}
```

https://github.com/supabase/ui/blob/989b9ed73fa773e50798638ee75aa4c42a45d1e0/src/components/Badge/Badge.tsx#L33-L35

**Comment by MildTomato** [comment]
### Supabase UI is being deprecated.

As part of that, we are closing issues in this repo that are perhaps outdated.

If you'd like to still make an issue, you could consider making an issue for our package in our monorepo https://github.com/supabase/supabase/tree/master/packages/ui

---

We are moving the components to the main mono repo at [https://github.com/supabase/supabase](https://github.com/supabase/supabase).

The auth component has been moved to it's own repo and package. [https://github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).
