### ISSUE TITLE
ADD @supabase/ui missing license on NPM

### ISSUE THREAD

**Issue by wscourge** [supabase/ui#387]
# Improve documentation

## Link 

[npm @supabase/ui](https://www.npmjs.com/package/@supabase/ui)

## Describe the problem

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/16985871/221348716-f9efce91-9069-4911-b6e9-7f27b59fd3a7.png">

## Describe the improvement

Add it. Is it Apache-2.0, same as this repository?

## Additional context

None

**Comment by itsajay1029** [comment]
I'd love to work on this. Pls assign it to me @wscourge

**Comment by wscourge** [comment]
I'm not a contributor on this repo, merely an issue reporter.

**Comment by MildTomato** [comment]
### Supabase UI is being deprecated.

As part of that, we are closing Pull Requests in this repo for now.

If you'd like to still make these changes, you could consider making these changes in https://github.com/supabase/supabase/tree/master/packages/ui

---

We are moving the components to the main mono repo at [https://github.com/supabase/supabase](https://github.com/supabase/supabase).

The auth component has been moved to it's own repo and package. [https://github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).
