### ISSUE TITLE
Importing via ESM fails

### ISSUE THREAD

**Issue by netgfx** [supabase/ui#388]
# Bug report

## Describe the bug

When trying to import via  `import { Input } from "@supabase/ui"` loaded via ESM on platforms like Framer I get:
`Error: Module not found: https://ga.jspm.io/npm:@supabase/ui@0.36.5/dist/esm/node_modules/@headlessui/react/dist/hooks/use-sync-refs.esm.js imported from https://ga.jspm.io/npm:@supabase/ui@0.36.5/dist/esm/node_modules/@headlessui/react/dist/components/disclosure/disclosure.esm.js`

Same thing when trying to load it on jspm online generator: https://generator.jspm.io/#Y2NhYGBkDM0rySzJSU1hcCguLUhMSixO1S/NdDDQMzbTMwUAceA5iyIA

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. add `import { Input } from "@supabase/ui"`
2. on a platform that doesn't support npm install

## Expected behavior

No errors and UI element be able to render

## System information

- OS: Windows
- Browser (if applies) Chrome
- Version of supabase-js: 0.36.5
- Version of Node.js: unavailable

## Additional context

**Comment by MildTomato** [comment]
### Supabase UI is being deprecated.

As part of that, we are closing Pull Requests in this repo for now.

If you'd like to still make these changes, you could consider making these changes in https://github.com/supabase/supabase/tree/master/packages/ui

---

We are moving the components to the main mono repo at [https://github.com/supabase/supabase](https://github.com/supabase/supabase).

The auth component has been moved to it's own repo and package. [https://github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).
