### ISSUE TITLE
Update Supabase to Support React 18

### ISSUE THREAD

**Issue by walifile** [supabase/ui#394]
I would like to request an update to the Supabase library to ensure compatibility with React 18. With the latest release of React, version 18, many projects are migrating to this new version for its performance improvements and new features. However, when attempting to use Supabase with React 18, a dependency conflict arises due to the specified peer dependency range of React in the Supabase library.

Currently, Supabase requires React versions "^16.13.1 || ^17.0.1", which does not include compatibility with React 18. This prevents users who have adopted React 18 from utilizing Supabase in their projects without workarounds such as forcing dependencies or downgrading React versions.

I kindly request that the Supabase library be updated to support React 18. This update would greatly benefit the developer community by allowing seamless integration of Supabase into projects leveraging the latest version of React. It would ensure a smoother development experience and help to keep projects up-to-date with the latest advancements in both Supabase and React.

Thank you for your consideration.

**Comment by Isaiah-Hamilton** [comment]
Supabase UI has been deprecated and wont be updated. The new location for supabase UI is [here](https://github.com/supabase/supabase/tree/master/packages/ui) and is now an in house package.
