### ISSUE TITLE
Error is thrown for Icon component if provided type prop does not match any from feathericons

### ISSUE THREAD

**Issue by joshenlim** [supabase/ui#42]
# Bug report

The following error gets thrown when I do something like `<Icon type="something" />` 

![image](https://user-images.githubusercontent.com/19742402/103981099-156b7f00-51bc-11eb-98fc-e93ac3969d0e.png)

Perhaps it should just not show anything? or return an error message that the type does not exist

**Comment by MildTomato** [comment]
Will make it default to a random icon if string isn't recognised
