### ISSUE TITLE
Icon supports src file path

### ISSUE THREAD

**Issue by phamhieu** [supabase/ui#48]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently `Icon` component only supports feather icon pack using `type` prop.

```
<Icon type:'Loader' />
```

Can we support `src` file path to svg file?

**Comment by MildTomato** [comment]
@phamhieu for this, would it be best to have something like the following 

```
import svgFile from './iconFile.svg`

// ...

<Icon src={svgFile}/>
```

**Comment by phamhieu** [comment]
Yes, that will be great

**Comment by MildTomato** [comment]
@phamhieu this is in the new release 👍 

you can still use the other props, like: size, stroke, fill to control how the icon looks.
stroke width will not work though

```javascript

import svgFile from './iconFile.svg'

// ...

<Icon src={svgFile} size={'large'} stroke={'red}/>
```
