### ISSUE TITLE
Button text still hard to read

### ISSUE THREAD

**Issue by kiwicopple** [supabase/ui#59]
# Chore

## Describe the chore

<img width="182" alt="image" src="https://user-images.githubusercontent.com/10214025/104407094-d2365500-559b-11eb-925c-dbd029c6d100.png">

It's still a bit hard to read the text on the green button. It looks like there is a shadow there, but perhaps it's an inner text shadow? I think a better strategy is to take the button color, then `darken()` it 40% or so, and make that a text-shadow. (this is how the old stripe site used to do it, and it seems to work best on soft/light colors)

For comparison

inner shadow:

<img width="165" alt="image" src="https://user-images.githubusercontent.com/10214025/104407446-9223a200-559c-11eb-831d-27a6ecdccefb.png">

drop shadow: 

<img width="181" alt="image" src="https://user-images.githubusercontent.com/10214025/104407478-a23b8180-559c-11eb-869d-41fe4d24bbcf.png">

**Comment by MildTomato** [comment]
it was 2 shades darker originally (@phamhieu originally pointed this out 👍 ) - I would prefer a darker bg color than using a drop shadow if that's all ok with everyone

**Comment by kiwicopple** [comment]
> I would prefer a darker bg color

do you mean the green?

**Comment by MildTomato** [comment]
Ah sorry, i mis read the above.

The inner shadow was a personal choice - just a personal preference. It will probably look great with a darker background.

If you folks prefer a drop shadow instead though I can change it though 😄

**Comment by MildTomato** [comment]
> do you mean the green?

yep

**Comment by kiwicopple** [comment]
I just think it's more legible if it's a text-shadow, especially on the small buttons. so not really a preference as much as a practicality - as far as I can tell: 

- inner shadows "eat into" the text, blurring the text edges)
- drop shadows define the text edges, making them look sharper

**Comment by MildTomato** [comment]
@kiwicopple added drop shadow and using original button bg color

![Screenshot 2021-01-13 at 13 27 42](https://user-images.githubusercontent.com/8291514/104410382-2a248a00-55a3-11eb-8cee-28c79c2c9426.png)

**Comment by kiwicopple** [comment]
I added a comment to the PR - I think the main issue is that the drop shadow is black, which means it has to be very light so that it doesn't conflict with the button color. If we can somehow use a darker version of the button that would be awesome (once again something I figured out from the old stripe site). Then it doesn't actually matter how light the button is, because the shadow gives it the contrast.

The darker primary color is definitely easier to read though, even with the current shadow settings

**Comment by MildTomato** [comment]
@kiwicopple added text shadows using text color - once we have color theme variables we can use those easily to control the drop shadow as well 

![Screenshot 2021-01-13 at 14 32 27](https://user-images.githubusercontent.com/8291514/104415044-38c36f00-55ac-11eb-83fe-4e09ad923b23.png)

**Comment by kiwicopple** [comment]
yaaass, that is defo more readable. Nice one @MildTomato
