### ISSUE TITLE
Button sizes seem quite big

### ISSUE THREAD

**Issue by kiwicopple** [supabase/ui#60]
# Chore

## Describe the chore

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/10214025/104407618-fe9ea100-559c-11eb-987f-664b89aaaf98.png">

the red button is the default size, save/cancel is "tiny". It seems that the default button is quite large right? I think we are going to end up with a lot of "tiny" buttons on our dashboard

**Comment by kiwicopple** [comment]
For reference:

<img width="838" alt="image" src="https://user-images.githubusercontent.com/10214025/104408237-9650bf00-559e-11eb-9ecd-5578c8eaff7e.png">

**Comment by MildTomato** [comment]
We probably should use 'small' or 'tiny' as default - just so we don't have to keep adding a size prop, and stop large buttons creeping in.

cc @phamhieu let us know if you've got any problems with this

**Comment by MildTomato** [comment]
using `tiny` as default. releasing.
