### ISSUE TITLE
[Auth] Persist email and password state across sign in and sign up

### ISSUE THREAD

**Issue by thorwebdev** [supabase/ui#72]
# Feature request

## Is your feature request related to a problem? Please describe.

When someone types in email and password in the sign in screen but doesn't have an account and then clicks on sign up, the email and password input fields are cleared and they have to retype it.

## Describe the solution you'd like

Persist email and password states between sign in and sign up views

**Comment by menor** [comment]
I think I have this working but not sure how to make the Pull Request, should I branch out from `develop` or create a fork? 
The branch should be named something as `feature/persist-form-data` and use semantic commit, right?

**Comment by MildTomato** [comment]
hey @menor, thanks for taking this one 👍 

yep, we use semantic release to trigger releases. so if one of your commits has `"fix: rest of commit message...` as your commit message, that would trigger a patch release. which would be perfect for this.

To create a pull request, create a fork and then you should be able to [pull request the changes from your fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by MildTomato** [comment]
@menor for branch naming it probably makes more sense to have it under `chore/auth-persist-form-data` or `fix/auth-persist-form-data` since it's not really a full feature.

**Comment by menor** [comment]
Thanks, hope I did everything right, but let me know if missed something
https://github.com/supabase/ui/pull/138
