### ISSUE TITLE
[Auth] Add message for sign up email confirmation

### ISSUE THREAD

**Issue by thorwebdev** [supabase/ui#73]
# Feature request

Currently the auth component does not give a message when signing up when confirmation email is enabled.

We should add "Check your email for the confirmation link." as a message

**Comment by dragos199993** [comment]
Hello. Is this still required. I can take a look into this. Thanks.
What do you guys say about adding the option on what message to be displayed. In that way the user can pass the text as a translation. <Component signUpMessage="t('success.signup')' /> something like this. If that property doesn't exist, the current it uses the current behavior.

**Comment by Ayan-Bandyopadhyay** [comment]
Could we make this message show up in a popup modal or even just show up in red? Right now it's really subtle and easy to miss.

**Comment by modsushi** [comment]
that email sent message is not a good UX. I shipped this and a lot of users just didn't see it. ideally expose a callback so we can show a toast or something
