### ISSUE TITLE
Select component has overlapping icons on the far right

### ISSUE THREAD

**Issue by joshenlim** [supabase/ui#76]
# Bug report

Version: 0.6.1

There seems to be 2 icons overlapping - one in a `<span>` while the other as a background-image for the Select component

![image](https://user-images.githubusercontent.com/19742402/104847233-c8a14a00-5919-11eb-80a8-6e1a6a9b13f2.png)

**Comment by joshenlim** [comment]
Did a bit of digging - this is cause I'm using the `select` wrapped within a `form` element, and tailwindcss has its own innate class style to give that down chevron for all select fields

**Comment by MildTomato** [comment]
@joshenlim i'll take a look 👍

**Comment by MildTomato** [comment]
fixed in next release.
