### ISSUE TITLE
Input component to support autofocus prop

### ISSUE THREAD

**Issue by joshenlim** [supabase/ui#77]
# Feature request

Wondering if we could add the support for autofocus for the input component

**Comment by MildTomato** [comment]
@joshenlim yes! absolutely, we should support this.

notes for task -
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefautofocus
https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/autofocus

just noting here as well, we should probably use markup such as `<dialog>`on modals and side panels to help trigger autofocus in forms when they are displayed.
