### ISSUE TITLE
feature: danger variant for button

### ISSUE THREAD

**Issue by phamhieu** [supabase/ui#9]
# Feature request

## Is your feature request related to a problem? Please describe.

For delete, remove action, we need a danger variant button

**Comment by MildTomato** [comment]
already done in feature branch im working on 🚀  
(although `variant` is being renamed to `type`) 

example use
```
<Button type="danger">I am the danger</Button>
```

will assign PR to this issue

**Comment by phamhieu** [comment]
I still can't find `danger` type on Button component.

**Comment by MildTomato** [comment]
@phamhieu sorry, your right, fixing

**Comment by MildTomato** [comment]
![Screenshot 2021-01-05 at 20 20 11](https://user-images.githubusercontent.com/8291514/103646393-8f212400-4f94-11eb-88ce-6ea7785dafa4.png)

also missing this type of button

**Comment by MildTomato** [comment]
@phamhieu 

`danger` is now a boolean prop. Took some inspiration from Antd.
danger can be applied to any type of button now.

```
<Button type="primary" danger>I am the danger</Button>
```
