### ISSUE TITLE
Disabled Toggle buttons are still able to be triggered

### ISSUE THREAD

**Issue by joshenlim** [supabase/ui#90]
# Bug report

If a toggle is disabled, clicking it should not trigger the provided `onClick` function prop

`<Toggle disabled onClick={() => console.log('hello')} />`

**Comment by mrkldshv** [comment]
Hey @joshenlim! I'm willing to help with this one, however I wasn't able to reproduce it. Any tips here?

**Comment by joshenlim** [comment]
oh hey @mrkldshv! i just checked it again - i think it might have been fixed in a recent release. Thanks so much though - real appreciate :) will be closing this
