### ISSUE TITLE
feat: support for justify-content: space-between in Button

### ISSUE THREAD

**Issue by MildTomato** [supabase/ui#91]
![Screenshot 2021-01-20 at 22 47 06](https://user-images.githubusercontent.com/8291514/105192191-d1408d00-5b72-11eb-8b87-23e1d45a6d87.png)

**Comment by MildTomato** [comment]
not required.

if anyone likes different layouts feel free to reopen this issue with some comments

**Comment by MildTomato** [comment]
@awalias reopening

**Comment by awalias** [comment]
sorry didn't see this before

when the button is part of centrally aligned content like on the dashboard, it looks like a mistake

<img width="897" alt="image" src="https://user-images.githubusercontent.com/458736/106433473-3b2e3000-64ab-11eb-8e0d-6712b45ceeeb.png">

**Comment by MildTomato** [comment]
It's cool 😎 I think it would be quite useful for things like login / sign up buttons
