### ISSUE TITLE
Feat: Support for Copy in Input

### ISSUE THREAD

**Issue by MildTomato** [supabase/ui#94]
Possibly also add support in Typography components.

We can add this in as a boolean optional prop

super fast mockup:
![Screenshot 2021-01-25 at 17 09 04](https://user-images.githubusercontent.com/8291514/105684595-23e1c680-5f30-11eb-87fa-c120730f83f4.png)

**Comment by kiwicopple** [comment]
It could be good to have support for a generic button (not just copy), so that we can do things like "reveal" etc

**Comment by MildTomato** [comment]
> It could be good to have support for a generic button (not just copy), so that we can do things like "reveal" etc

Opened that up in another issue #96

**Comment by MildTomato** [comment]
Closing this as it's now a duplicate of #96
