### ISSUE TITLE
Feat: Reveal and Copy in Inputs

### ISSUE THREAD

**Issue by MildTomato** [supabase/ui#96]
# Feature request

## Is your feature request related to a problem? Please describe.

On a projects Settings -> API view, it's pretty easy to accidentally copy the "service_role" API key instead of the "public" one despite the "secret" label.

## Describe the solution you'd like

• It'd be great if the "service_role" API key were obscurbed with "***" be default. Then, add a "Reveal" button to allow the user to see/copy it.

• It could be good to have support for a generic button (not just copy), so that we can do things like "reveal" etc

_Originally posted by @kiwicopple in https://github.com/supabase/ui/issues/94#issuecomment-765815273_

_Originally posted by @calendee #99 
![105686508-3ab3f900-5eef-11eb-9561-51055439b3ed](https://user-images.githubusercontent.com/8291514/105688014-162e4000-5f34-11eb-9540-f66c82e1574a.png)

## UI solutions

use a button inside input
![105659014-b66b7100-5f02-11eb-8991-c5f4eabfaf17](https://user-images.githubusercontent.com/8291514/105688121-31994b00-5f34-11eb-9a88-dc250538cc71.png)

![Screenshot 2021-01-25 at 17 09 04](https://user-images.githubusercontent.com/8291514/105688032-1a5a5d80-5f34-11eb-83d7-3ef67c259f0a.png)

would also need to support both at the same time - or perhaps, `copy` button is not visible unless `reveal` is clicked first

**Comment by mrkldshv** [comment]
Hey @MildTomato!

I'd like to help with this one! Also I'd like to hear your thoughts or suggestion on this: 
* should we extend currently implemented input and just make this button as optional prop? 
* I imagine placing this button on right side of the input. What do you think? 
* Probably we should also allow putting some text within this button?

**Comment by MildTomato** [comment]
Hey @mrkldshv - sounds great! here's some of my thoughts and suggestions..

> should we extend currently implemented input and just make this button as optional prop?

yep, that sounds good to me. I was originally thinking we just have this optional prop a callback, but then we would need another prop to determine what the label of the button should be.

It might be better to have the prop just allow for any react.node, and anyone could just insert what they like (most likely a <Button> component).

I might have already half solved this [with this PR](https://github.com/supabase/ui/pull/87)
with these changes (i haven't finished it yet..) we can insert something on the left or the right of the input.

however, maybe it's good to have another prop for this, so that anyone could just insert something on the right side of the Input.

very quick mockup of what it might end up looking like:
![Screenshot 2021-01-25 at 11 43 53](https://user-images.githubusercontent.com/8291514/105659014-b66b7100-5f02-11eb-8991-c5f4eabfaf17.png)

example code:
```JS
<Input 
  value={value} 
  optAction={[
    <Button size="tiny" type="outline" onClick={revealValue}>Reveal</Button>
  ]}
/>
```

**Comment by MildTomato** [comment]
just for future reference - also mentioned in #99 about reveal functionality

**Comment by MildTomato** [comment]
@mrkldshv [I tried it out](https://github.com/supabase/ui/pull/100) with optional props for both copy and reveal 😄

**Comment by mrkldshv** [comment]
@MildTomato cool, looking nice 👍 I like the ideas, you mentioned above. By the way, do you think it might be better to make these props more generic? I mean to allow user put any button or label on the left/right side of the input.

**Comment by MildTomato** [comment]
@mrkldshv I think you're right - I think it might be better to just have a ReactNode based prop, so anyone can just put in whatever they like, and then they're not stuck with the default button styling etc.

And then the Input component isn't stuffed with code that might never get used.

**Comment by mrkldshv** [comment]
@MildTomato awesome, I see it's released now 🚀 We can think of adding option to have it on the right hand side as well in one of the future MRs.

**Comment by MildTomato** [comment]
@mrkldshv absolutely 🚀  ! 

If you want to have a crack at it and submit a pull request that would be awesome 👍 
saying that, I'll open up some more issues with Inputs, as there's quite a lot of other things I overlooked beforehand which might benefit with someone else's input (pun intended... 😬 )

Thanks for the feedback - it was super helpful
